### ISSUE TITLE
Exapandable gorup arrow rotateing in first load

### ISSUE THREAD

**Issue by sagarchavda** [thoughtbot/expandable-recycler-view#105]
Hello,

I'm Add data at run-time in navigation drawer and initialize it. Now, when first time i open navigation drawer arrow immediately arrow rotate to expand then collapse view. Arrow already initialized on collapse view.  Now, how can i reproduce this? Please guide me and if needed and i ready to share necessary code.

Yes, i done few changes for open only one group at once and it's working fine.

Thanks

**Comment by RobertoIDL** [comment]
Hi,

I was wondering how you solved this problem. I'm facing the same issue. All the arrows animate when I first open the list.

And also when I expand the first group and the scroll I can see the arrows animating again, it's like it doesn't distinguish if that list was already expanded or not

Regards.
