### ISSUE TITLE
onBindChildViewHolder not being called

### ISSUE THREAD

**Issue by devtechvalens** [thoughtbot/expandable-recycler-view#106]
onBindChildViewHolder & onCreateChildViewHolder are not being called.

**Comment by mandybess** [comment]
Can you provide code samples or more information here? When are they not being called?

**Comment by karan14jan** [comment]
onBindChildViewHolder & onCreateChildViewHolder are not being called.

**Comment by karan14jan** [comment]
make parent view and child view layout height wrap_content

**Comment by pratim-navsoft** [comment]
onBindChildViewHolder & onCreateChildViewHolder are not being called.

**Comment by ashish-dhiman-net** [comment]
I was also implementing com.thoughtbot.expandablerecyclerview. What I did in the same scenario was, in the custom class that is extending ExpandableGroup, I override getItems() and getItemCount() methods and provided the values which I wanted as "child"-expanded state.

**Comment by hpatel123** [comment]
Still having the same issue. Can anyone help ?

**Comment by ashish-d-hh** [comment]
In the class, that extends extends ExpandableGroup<Some_Type_Of_Class>
Override following: Using Ctrl+O
`
@Override
    public List<QuestionairreOption> getItems() {
        return options;
    }

    @Override
    public int getItemCount() {
        return options.size();
    }
`

**Comment by thaiquoctoanvn** [comment]
> In the class, that extends extends ExpandableGroup<Some_Type_Of_Class> Override following: Using Ctrl+O ` @OverRide public List getItems() { return options; }
> 
> ```
> @Override
> public int getItemCount() {
>     return options.size();
> }
> ```
> 
> `

You're right. I got the same problem. When I use the Child item with just one parameter, everything went well. Then I started to use a Child object that also be used in my retrofit structure like this

```
@Parcelize
    data class Child(
        @SerializedName("id")
        val id: Int,
        @SerializedName("name")
        val name: String,
        @SerializedName("description")
        val description: String,
        @SerializedName("url")
        val url: String
    ) : Parcelable
```
And the trouble happened. To solve the problem, just do like [ashish-d-hh's solution](https://github.com/thoughtbot/expandable-recycler-view/issues/106#issuecomment-913651830). In my case I just add only getItemCount method to Parent object and enjoy!
