### ISSUE TITLE
How to get group and child position from flatPos in setOnGroupClickListener

### ISSUE THREAD

**Issue by GaniduAsh** [thoughtbot/expandable-recycler-view#107]
setOnGroupClickListener function will returns the position of onClick you make. But   the flatPos will returns the location not only the group but with child position . is there anyway that can get the group position . ??  i saw that ExpandableListPosition . can do that , but no idea how it can be done

**Comment by shadowpath** [comment]
I made a method to get the real group position from group item and flat position:

private int calculateRealGroupPosition(ExpandableGroup group, int flatPosition) {
        int realPos = flatPosition;

        int groupsBefore = 0;
        List<? extends ExpandableGroup> groups = getGroups();

        for (ExpandableGroup expandableGroup : groups) {
            if (expandableGroup.equals(group)) {
                break;
            }
            groupsBefore++;
        }

        for (int i = 0; i < groupsBefore; i++) {
            InterviewSectionRecyclerItem groupItem = getGroupItem(i);
            if (isGroupExpanded(groupItem)){
                realPos -= groupItem.getItemCount();
            }
        }

        return realPos;
    }

**Comment by lengsovandara** [comment]
Can you explain this line.
InterviewSectionRecyclerItem groupItem = getGroupItem(i);

**Comment by ganjarramadhan** [comment]
Just wondering if someone still looking for a solution, i solved this issue by modify @shadowpath solution

`private fun calculateRealGroupPosition(group: ExpandableGroup<*>, flatPosition: Int): Int {
        var realPos = flatPosition

        val groupsBefore = arrayListOf<ExpandableGroup<*>>()
        val groups = groups

        for (expandableGroup in groups) {
            if (expandableGroup == group) {
                break
            }
            groupsBefore.add(expandableGroup)
        }

        for (i in 0 until groupsBefore.size) {
            val groupItem = groupsBefore[i]
            if (isGroupExpanded(groupItem)) {
                realPos -= groupItem.itemCount
            }
        }

        return realPos
    }`

**Comment by lengsovandara** [comment]
@ganjarramadhan Thank you

**Comment by GaniduAsh** [comment]
thanks for the reply i managed to get it done customizing a different lib,

**Comment by bkhong87** [comment]
Not sure if this helps.
use expandableList.getFlattenedGroupIndex(group) method to get real group position.

    @Override
    public void onBindChildViewHolder(MenuChildViewHolder holder, int flatPosition, ExpandableGroup group, int childIndex) {
        holder.setChildAdapter(menuChildModel.getName(), expandableList.getFlattenedGroupIndex(group), childIndex);

    }

**Comment by srinivasancp** [comment]
@ganjarramadhan can you please provide this in Java?
