### ISSUE TITLE
Why minSdkVersion 16?

### ISSUE THREAD

**Issue by abunayem** [thoughtbot/expandable-recycler-view#108]

**Comment by aya-salama1989** [comment]
at least support APIs 15 please.

**Comment by rustyhamsterr** [comment]
Hi, if you need lower sdk version, you can build it yourself. At least I could do so for API 15. I was able to run the provided sample app without having issues so far. I don't know which api is really needed for the functionality, but 15 is working so far.
To try, 

- change all build.gradle minSdk entries to your desired API level

-  Keep in mind to update module `expandablecheckrecyclerview` as the online dependency of `expandablerecyclerview` has minSdk16 replace with local dependecy on module:` compile project(':expandablerecyclerview'))`
