### ISSUE TITLE
Adapter.toggleGroup(group) doesnt call collapse or expand animation in groupViewholder

### ISSUE THREAD

**Issue by jet360** [thoughtbot/expandable-recycler-view#109]
calling.toggleGroup(group) doesnt call the collapse or expand method in the groups Viewholder

**Comment by mandybess** [comment]
Line 36 of ExpandActivity in the sample app is intentionally disabling the animation to the GenreViewHolder. Here is the full code from that line with the comment explaining why:

    // RecyclerView has some built in animations to it, using the DefaultItemAnimator.
    // Specifically when you call notifyItemChanged() it does a fade animation for the changing
    // of the data in the ViewHolder. If you would like to disable this you can use the following:
    RecyclerView.ItemAnimator animator = recyclerView.getItemAnimator();
    if (animator instanceof DefaultItemAnimator) {
      ((DefaultItemAnimator) animator).setSupportsChangeAnimations(false);
    }
If you delete the setSupportsChangeAnimations line the rotation animation will work.

When callingadapter.toggle() the adapter passes that call through to the ExpandCollapseController who in turns calls through to the ExpandCollapseListener which the ExpandableRecyclerViewAdapter implements. If you look at theonGroupCollapsed() implementation in ExpandableRecyclerViewAdapter you can see that it calls notifyItemChanged on the header - which forces a call to onBindViewHolder which handles calling either expand or collapse on the GroupViewHolder. It's admittedly a little confusing to follow but this solution ensures both click events and programatic toggles will lead to the expand() and collapse() functions to be called.

**Comment by ankitgoyal1009** [comment]
I have implemented it for expanding one section at a time and on expanding one section other one will collapse. if a section is expanded then on back button press i collapse the section. functionality wise this setup is working except rotation animation.
I have not implemented default animator. I have noticed same behaviour If i expand different section then previous section gets collapsed but rotation animation does not work until I scroll list.
I will be glad if you can put more light on how can I achieve this.
