### ISSUE TITLE
saved state with fragments

### ISSUE THREAD

**Issue by IlanVokov** [thoughtbot/expandable-recycler-view#11]
the save state does not work with fragments

**Comment by mandybess** [comment]
hi @IlanVokov ! What Fragment lifecycle call backs were you trying??

**Comment by IlanVokov** [comment]
onSaveInstanceState to save as you do, and there is no onRestoreInstanceState in fragment so i try inside onCreateView

**Comment by eurbon** [comment]
I know I'm a little late but today I managed to sort this problem out so thought it would be good to share the solution.  

So basically the idea is in onCreate method to either load items list from a saved instance between rotation changes OR  if app was launched first time, savedInstance will be null so fragment needs to retrieve items ist from network.


in onCreate method:  

```
@Override
public void onCreate(@Nullable Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
if (savedInstanceState != null) {
itemsList = (SmartmeterResponse) savedInstanceState.getSerializable("ITEMS");
adapter = new Adapter(itemsList);
adapter.onRestoreInstanceState(savedInstanceState);
} else {
//Do your network calls, retrieve items list and instantiate adapter 
}
```
In onCreateView you bind your adapter to recyclerView.  
```
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
//Inflate view, create recyclerView/Adapter references
//Create adapter by using itemsList (either retrieved from network or from your savedInstance)
//Bind adapter to recyclerView
}
```

Then in onViewStateRestored method:  

```
    @Override
    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
        super.onViewStateRestored(savedInstanceState);
        if (savedInstanceState != null)
            adapter.onRestoreInstanceState(savedInstanceState);
    }
```

in onSaveInstance method:

```
    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        adapter.onSaveInstanceState(outState);
        outState.putSerializable("ITEMS", itemsList);
    }
```

And that's about it.

**Comment by haiminhtran810** [comment]
Sorry, Can you question ?
About lost state when ExpandableRecycleview scrolls then All it`values will be wrong.
Example
When 1 item VISIBLE or GONE . when I scroll . VISIBLE AND  GONE wrong. 
Thankyou

**Comment by eurbon** [comment]
@haiminhtran810  Sorry I dont understand. Ask your friend who speaks english to clarify.

**Comment by haiminhtran810** [comment]
@eurbon Sorry you
I encountered a case that when I scroll down/up it loses state
For example :
I have a List<Data> (1: visible , 2 visible,3 visible, 4 visible, 5 visible, 6 invisible)
I have a layout_item_parent
Include : 
ImageView ( invisible or visible ) and TextView. 
But when I dont scroll, Imageview is visible . Then I scroll down then i scroll up. Show ImageView wrong
It change to visible to Invisible
Sorry you. My weak English
