### ISSUE TITLE
Group view type issue

### ISSUE THREAD

**Issue by yarmobile** [thoughtbot/expandable-recycler-view#111]
Trouble begins, when one tries to implement multiple GROUP view types. No example is given.
ExpandableGroup class does not have some field like "type". How can one distinguish the view type in 
`public int getGroupViewType(int position, ExpandableGroup pGroup)`
?  By title?

**Comment by mandybess** [comment]
You could use type inference. I.e. `if (pGroup instanceOf ExpandableGroupSubclass)` where `ExpandableGroupSubclass` is an extension of `ExpandableGroup`.

Hope that helps 👍
