### ISSUE TITLE
Class cast Exception when passing same custom arraylist to another activity

### ISSUE THREAD

**Issue by atul-forbinary** [thoughtbot/expandable-recycler-view#112]
ClassCastException: com.thoughtbot.expandablerecyclerview.models.ExpandableGroup cannot be cast to utils.CustomProduct

**Comment by mandybess** [comment]
Just checking, does `CustomProduct` extend `ExpandableGroup`? Assuming it does, how are you passing it through? It should look like this:

## Adding to `Intent`:

```
intent.putParcelableArrayListExtra(GROUPS_EXTRA,(ArrayList<? extends Parcelable>) groups);
```

- where `groups` is `List<ExpandableGroup>`

## Retrieving from `Intent`:

```
groups = data.getExtras().getParcelableArrayList(GROUPS_EXTRA);
```
