### ISSUE TITLE
Horizontal Scroll View in ChildView

### ISSUE THREAD

**Issue by bootavo** [thoughtbot/expandable-recycler-view#117]
Hi thougtbot,

Well I implemented this library, but I need the Title of Lists are keep in top and ChilView it inside the Horizontal Scroll View, What can I do this?

I send you this image.

![screenshot_20171111-153307](https://user-images.githubusercontent.com/14097065/32693277-36b3ce6e-c6f6-11e7-9391-322f5c6d23e4.png)

**Comment by mf-mindcrewtech** [comment]
Hi @bootavo any update on this? i am searching for the same

**Comment by Hetal2011** [comment]
I am also searching for the same, can anyone help please!

**Comment by SyedAmmarSohail** [comment]
yes, I am also wait for it, please update new version which includes horizontal child view.
@Hetal2011 @bootavo @mf-mindcrewtech guys you found any solution for it?
