### ISSUE TITLE
How to disable the collapse functionality always

### ISSUE THREAD

**Issue by akhilmankala** [thoughtbot/expandable-recycler-view#118]

**Comment by ZUCheema** [comment]
override onGroupClick in your expandable adapter and return false.
Do not call super.onGroupClick(); 
Moreover, call setOnGroupClickListener(null); in your adapter constructor.

**Comment by EliorBenYosef** [comment]
just override onGroupClick() inside the adapter in this way:

    @Override
    public boolean onGroupClick(int flatPos) {
        if (isGroupExpanded(flatPos)) { // will disable group collapse
            return true;
        }
        return super.onGroupClick(flatPos);
    }
