### ISSUE TITLE
How i can show data from Json ???

### ISSUE THREAD

**Issue by iman100** [thoughtbot/expandable-recycler-view#123]
hi
how i can show in Expanadbale Recyclerview Data from json .I just show data static simple app in libery

ex:
```
public void getgroups() {
    groupExpandables = new ArrayList<>(6);
    for (int i = 0; i < 6; i++) {
      List<PersonExpandable> artists = new ArrayList<>(3);
      artists.add(new PersonExpandable("Andi"));
      artists.add(new PersonExpandable("Googoosh"));
      artists.add(new PersonExpandable("Yas"));
      groupExpandables.add(new ExpandableGroup("Rock_ " + i, artists));  }
}
```

**Comment by MohammadBarati** [comment]
`{
  "درخواست مساعده": [
    "درخواست مساعده"
  ]
  ,
  "درخواست مرخصی": [
     "مرخصی ساعتی",
    "مرخصی روزانه"
    ]
  ,
  "درخواست وجه": [
     "درخواست واریز وجه",
    "درخواست واریز"
    ]
  ,
  "درخواست ماموریت": [
     "درخواست ماموریت روزانه",
    "درخواست ماموریت روزانه"
    ]
  
}`

its my json and below is how u can move Data to this Library


`private void setDataChild() {
		try {
			List<Genre> genres = new ArrayList<>();
			JSONObject object = new JSONObject(json);
			JSONArray arrData = object.getJSONArray("result");
			for (int i = 0; i < arrData.length(); i++) {
				List<DataModelChild> allData = new ArrayList<>();
				JSONObject objData = arrData.getJSONObject(i);
				JSONArray arrItems = objData.getJSONArray("items");
				for (int j = 0; j < arrItems.length(); j++) {
					allData.add(new DataModelChild(String.valueOf(j), arrItems.getString(j), R.drawable.ic_mamoriat));
				}
				genres.add(new Genre(objData.getString("title"), String.valueOf(i), allData));
			}
			LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
			//instantiate your adapter with the list of genres
			GenreAdapter adapter = new GenreAdapter(genres, getContext());
			vRcList.setLayoutManager(layoutManager);
			vRcList.setAdapter(adapter);

		} catch (JSONException e) {
			e.printStackTrace();
		}
	}`

**Comment by dryaz** [comment]
Check this PR
https://github.com/thoughtbot/expandable-recycler-view/pull/162

You could be able to implement `Group` interface to let your own models be expandable in list.
