### ISSUE TITLE
How can I have a Group and its Children contained inside of a card?

### ISSUE THREAD

**Issue by kevincianfarini** [thoughtbot/expandable-recycler-view#127]
Right now I tried wrapping the layout for the group in a card that's height attribute is set to be `wrap_content`. However, the child components of the group are appended below the card. Is there something that I'm missing on how I would achieve this?

**Comment by akshaybhange** [comment]
Try this 

**Parent Card**
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="@dimen/main_card_margin_vertical"
    android:layout_marginTop="@dimen/main_card_margin_vertical"
    android:layout_marginRight="@dimen/main_card_margin_vertical"
    android:background="?attr/selectableItemBackground"
    android:foreground="?attr/selectableItemBackground">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/card_button_margin">
       //your views
    </RelativeLayout>

</android.support.v7.widget.CardView>`

**Child Card**
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:background="?attr/selectableItemBackground"
    android:foreground="?attr/selectableItemBackground">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/card_button_margin"
        android:layout_marginLeft="@dimen/card_button_margin"
        android:layout_marginEnd="@dimen/card_button_margin"
        android:layout_marginRight="@dimen/card_button_margin">
     //your views
    </RelativeLayout>

</android.support.v7.widget.CardView>`

**It will look like this**
![image](https://user-images.githubusercontent.com/39375914/54925970-62be2400-4f35-11e9-970f-6158ae061644.png)
