### ISSUE TITLE
Can't toggle all group at once by looping through

### ISSUE THREAD

**Issue by noman404** [thoughtbot/expandable-recycler-view#13]
Trying to toggle all groups which have child item. using 

adapter.toggleGroup(POSITION_WHICH_HAS_CHILD_ITEM);

**Comment by mjobanputra** [comment]
I have same issue...please provide some solution

**Comment by mandybess** [comment]
hi @noman404 and @mjobanputra 

Here is how you can toggle all groups:

```java
  public void toggleAllGroups() {
    for (int i = 0; i < expandableList.expandedGroupIndexes.size(); i++) {
      toggleGroup(getFlattenedGroupPosition(i));
    }
  }

  public int getFlattenedGroupPosition(int groupIndex) {
    int runningTotal = 0;
    for (int i = 0; i < groupIndex; i++) {
      runningTotal += numberOfVisibleItemsInGroup(i);
    }
    return runningTotal;
  }

  private int numberOfVisibleItemsInGroup(int group) {
    if (expandableList.expandedGroupIndexes.get(group)) {
      return expandableList.groups.get(group).getItemCount() + 1;
    } else {
      return 1;
    }
  }
```

The `toggleAllGroups` and `getFlattenedGroupPosition` method do not currently exist in the library. I will add both in the next version. The `numberOfVisibleItemsInGroup` method does exist within `ExpandableList` it is just private so you have to copy and paste it over. I will change it's scope in the next version as well.

**Comment by mjobanputra** [comment]
Problem is that when we call toggleGroup() it does not call expand() or collapse() in GoupViewHolder.
expand() and collapse() only calls when we click on groupViewHolder item. can you please provide some solution for it??
