### ISSUE TITLE
How could i expand the first group by default.

### ISSUE THREAD

**Issue by akshaykumar0291** [thoughtbot/expandable-recycler-view#131]
Hi, thank you for the tutorial. How could i expand the first group by default when displaying the list very first time and it should collapse after expanding any other group.

**Comment by rustyhamsterr** [comment]
Hi, assuming your code is build upon the sample app, the call would happen in the activity.
After the adapter is set the method `toggleGroup(int flatPos)` (substitute flatPos with 0 for first element) can be called, so right after the adapter is set
This should result in an expanded first group everytime the containing Activity or Fragment is build.
The method is part of ExpandableRecyclerViewAdapter class and so it is available to every sub-type adapter.
If there are further questions or if I missed the point of your question, keep asking ;)

**Comment by sameerkhader** [comment]
Hi,
if i want all group to be expand

**Comment by VuHongKy** [comment]
@sameerkhader You can do like that:
1. On activity (or fragment)
`recyclerView.viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
            override fun onGlobalLayout() {
                recyclerView.viewTreeObserver.removeOnGlobalLayoutListener(this)
                adapter.expandAllGroups()
            }
        })`

2. On adapter
`fun expandAllGroups() {
        groups.forEachIndexed { groupIndex, group ->
            if (isGroupExpanded(group).not()) {
                onGroupClick(expandableList.getFlattenedGroupIndex(groupIndex))
            }
        }
    }`

With this way, you can expand all groups or some groups if you want.
Sorry I am using Kotlin, so you should try to understand it. Thank you!

**Comment by paatz04** [comment]
Calling toggleGroup(0) gives me a     
java.lang.RuntimeException: Unknown state

**Comment by kaysho** [comment]
I'm having edit text in my expandable recycler view, what I want to achieve is to save the values of inside the edit text for later use to save, I'm finding it difficult to achieve with expandable recycler view

**Comment by asayesm** [comment]
Adapter

public class RespuestaAdapter extends ExpandableRecyclerViewAdapter<PreguntaViewHolder, RespuestaViewHolder> {
    List<? extends ExpandableGroup>  grupo;

    public RespuestaAdapter(List<? extends ExpandableGroup> groups){
        super(groups);
        grupo = groups;
    }

    @Override
    public PreguntaViewHolder onCreateGroupViewHolder(ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_pregunta,parent,false);
        return new PreguntaViewHolder(v);
    }

    @Override
    public RespuestaViewHolder onCreateChildViewHolder(ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_respuesta,parent,false);
        return new RespuestaViewHolder(v);
    }

    @Override
    public void onBindChildViewHolder(RespuestaViewHolder holder, int flatPosition, ExpandableGroup group, int childIndex) {
        final RespuestaModel respuestaModel = (RespuestaModel) group.getItems().get(childIndex);
        holder.bind(respuestaModel);
    }

    @Override
    public void onBindGroupViewHolder(PreguntaViewHolder holder, int flatPosition, ExpandableGroup group) {
        final PreguntaModel preguntaModel = (PreguntaModel) group;
        holder.bind(preguntaModel);
    }

    public void expandAllGroups(){

        for(int i = 0;i<grupo.size();i++){
            if (!isGroupExpanded(grupo.get(i))) {
                onGroupClick(expandableList.getFlattenedGroupIndex(i));
            }
        }
    }
}

==================
Activity o Fragment

final RespuestaAdapter adapter = new RespuestaAdapter(listadoP);
        listadoPreguntas.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                                                                             @Override
                                                                             public void onGlobalLayout() {
                                                                                 listadoPreguntas.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                                                                                 adapter.expandAllGroups();
                                                                             }
                                                                         });


                listadoPreguntas.setAdapter(adapter);

**Comment by fi8er1** [comment]
toggleGroup(); won't call expand in GroupViewHolder... I need to animate the arrow icon programmatically as well...

**Comment by Nepalec** [comment]
My problem is that I have groups with arrows indicating their state:
<img width="312" alt="Screen Shot 2020-07-15 at 5 18 10 PM" src="https://user-images.githubusercontent.com/3699480/87556454-58daaa00-c6bf-11ea-8edb-b8781030cdac.png">
Now I need one group to be expanded on startup. What I try to do is groupsAdapter.onGroupClick(groupToBeOpenedIndex); 

it opens the group, however arrow to the right remains in the wrong state.

How can I make the arrow to be changed to opened state when I do "onGroupClick()" or "toggleGroup"  ???
