### ISSUE TITLE
Exception returning to Activity after a new Group has been added

### ISSUE THREAD

**Issue by iyyel** [thoughtbot/expandable-recycler-view#132]
Greetings. I'm having an issue with updating the ExpandableRecyclerView after a new Group is added, resulting in an ArrayIndexOutOfBoundsException in ExpandableList. I know that there's other issues about updating the view, but I am making this issue since I am not quite sure if it is the same problem.

![image](https://user-images.githubusercontent.com/25253378/34537316-5e82e244-f0c8-11e7-8cbe-0f7188833a73.png)

This is how the single group currently looks unexpanded. All is good and fine. 

Now, if I add another Group to the Adapter's GroupArrayList, and then go back to the Activity shown in the picture, I get the following error:
![image](https://user-images.githubusercontent.com/25253378/34537490-e7d6faee-f0c8-11e7-8dd4-fe703443517d.png)

Is there a function that I can call, that tells the list to be updated, or something of the sort? How would I be able to handle this?

Thank you.

**Comment by fullmoon6661** [comment]
I got this issue too. Do you found the work around?

**Comment by iyyel** [comment]
@fullmoon6661 We changed to another library. :)

**Comment by fullmoon6661** [comment]
@iyyel yeah this library doesn't support updating the adapter unfortunately. Do you mind telling me what another library you use?

**Comment by iyyel** [comment]
@fullmoon6661 I just checked and apparently we just used expandable-listview with a lot of custom functionality.

**Comment by winniexuwen** [comment]
public void resetGroup(List<? extends ExpandableGroup> groups) {
        this.expandableList = new ExpandableList(groups);
        this.expandCollapseController = new ExpandCollapseController(expandableList, this);
    }

I add these code to ExpandableRecyclerViewAdapter class, and use it before adapter.notifyDataSetChanged();

**Comment by androidovshchik** [comment]
```
fun setAll(groups: List<Column>) {
    expandableList.groups = groups
    expandableList.expandedGroupIndexes = BooleanArray(groups.size)
}
```
This worked for me
```
adapter.setAll(data.columns)
adapter.notifyDataSetChanged()
```
