### ISSUE TITLE
onClickListener for specific viewholder

### ISSUE THREAD

**Issue by sebinpaul** [thoughtbot/expandable-recycler-view#136]
I want to implement onClickListener for a specific viewholder. Right now when I click on any item of the recyclerview the group expands. I want to limit this click to a viewholder. The group should only expand when I click this particular viewHolder. How do I do that?

**Comment by Balaje1408** [comment]
`class TitleViewHolder extends GroupViewHolder {
    TextView title_tv;
    CardView cardView;
    public TitleViewHolder(View itemView) {
        super(itemView);
        title_tv=(TextView)itemView.findViewById(R.id.title_index_tv);
        cardView=(CardView) itemView.findViewById(R.id.parentCardView);
    }

    public void setTitle(final ExpandableGroup group, final int flatPosition, final Context context, int contentModelSize){

        title_tv.setText((flatPosition+1)+") "+Html.fromHtml(group.getTitle()));

        if((contentModelSize-1)==flatPosition){
            cardView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    Toast.makeText(context,"Last Item "+flatPosition+" "+group.getItemCount(), Toast.LENGTH_LONG).show();
                }
            });

        }
    }
}
`
In this case, I want to Toast a message when the last item is clicked. So I passed the size of the list to be attached in recycler view to view holder. Then I compared it with flag position and displays toast.

**Summary:**
Pass the list of objects to view holder from adapter. compare list positions with flagPosition. Then perform operation as u want.
