### ISSUE TITLE
 The method for programmatically expanding a group does not call the expand () and collapse () methods

### ISSUE THREAD

**Issue by vitoramerico** [thoughtbot/expandable-recycler-view#137]
public class GenreViewHolder extends GroupViewHolder {

  private TextView genreName;
  private ImageView arrow;
  private ImageView icon;

  public GenreViewHolder(View itemView) {
    super(itemView);
    genreName = (TextView) itemView.findViewById(R.id.list_item_genre_name);
    arrow = (ImageView) itemView.findViewById(R.id.list_item_genre_arrow);
    icon = (ImageView) itemView.findViewById(R.id.list_item_genre_icon);
  }

  public void setGenreTitle(ExpandableGroup genre) {
    if (genre instanceof Genre) {
      genreName.setText(genre.getTitle());
      icon.setBackgroundResource(((Genre) genre).getIconResId());
    }
    if (genre instanceof MultiCheckGenre) {
      genreName.setText(genre.getTitle());
      icon.setBackgroundResource(((MultiCheckGenre) genre).getIconResId());
    }
    if (genre instanceof SingleCheckGenre) {
      genreName.setText(genre.getTitle());
      icon.setBackgroundResource(((SingleCheckGenre) genre).getIconResId());
    }
  }

  @Override
  public void expand() { 
    animateExpand();
  }

  @Override
  public void collapse() {
    animateCollapse();
  }

  private void animateExpand() {
    RotateAnimation rotate =
        new RotateAnimation(360, 180, RELATIVE_TO_SELF, 0.5f, RELATIVE_TO_SELF, 0.5f);
    rotate.setDuration(300);
    rotate.setFillAfter(true);
    arrow.setAnimation(rotate);
  }

  private void animateCollapse() {
    RotateAnimation rotate =
        new RotateAnimation(180, 360, RELATIVE_TO_SELF, 0.5f, RELATIVE_TO_SELF, 0.5f);
    rotate.setDuration(300);
    rotate.setFillAfter(true);
    arrow.setAnimation(rotate);
  }
}

the collapse () and expand () methods are not called when I use this function adapter.toggleGroup ()

**Comment by chetdeva** [comment]
You can create a var `expanded` in the `ExpandableGroup` and check it in `onBindGroupViewHolder` `if (group.expand) holder.animateExpand()` after you add this to the adapter:
```kotlin
    /**
     * Expands group if it is collapsed
     * @param groupPos position of group
     */
    fun expandGroupIfCollapsed(groupPos: Int): Boolean {
        val flatGroupPos = expandableList.getFlattenedGroupIndex(groupPos)
        if (!isGroupExpanded(flatGroupPos)) {
            categories[groupPos].expand = true
            notifyItemChanged(flatGroupPos)
            return super.toggleGroup(flatGroupPos)
        }
        return false
    }
```
Then call `adapter.expandGroupIfCollapsed(Int)`

**Comment by paveltech** [comment]
@chetdeva  can you please explain last function?
