### ISSUE TITLE
Fix for not working arrow rotations in expandablerecyclerview source

### ISSUE THREAD

**Issue by l2dev** [thoughtbot/expandable-recycler-view#139]
So basically if you remove **expandablerecyclerviewcheck**  project and in your sample project you try to rely on project  **expandablerecyclerview** like this **compile project(':expandablerecyclerview')** then you will have a bad time. When expanding the groups, arrows are just rotating 360 degrees and events are messed up.

I digged deeper and saw that **expandablerecyclerview**  project is relying on **expandablerecyclerviewcheck** project which in the gradle has a dependency on the repo **compile 'com.thoughtbot:expandablerecyclerview:1.3'**

After lots of trial and error I've concluded that the repo **'com.thoughtbot:expandablerecyclerview:1.3'** has this issue fixed, while in provided source it's not fixed.

 So here's what you need to do to fix this:

1. Go `com/thoughtbot/expandablerecyclerview/ExpandCollapseController.java`

Change:

`boolean expanded = expandableList.expandedGroupIndexes[listPos.groupPos];`

to:

`boolean expanded = isGroupExpanded(listPos.groupPos);`

2. Go `com/thoughtbot/expandablerecyclerview/ExpandableRecyclerViewAdapter.java`

Delete this block
	
```
       if (isGroupExpanded(group)) {	
          ((GVH) holder).expand();	
        } else {	
          ((GVH) holder).collapse();	
        }
```

Delete this block in onGroupExpanded Method

```
    //update header	
    int headerPosition = positionStart - 1;	
    notifyItemChanged(headerPosition);	
```

Delete this block in OnGroupCollapsed Metod

```
    //update header	
   int headerPosition = positionStart - 1;	
    notifyItemChanged(headerPosition);
```	

3. Go `com/thoughtbot/expandablerecyclerview/MultiTypeExpandableRecyclerViewAdapter.java`

Delete block

```
      if (isGroupExpanded(group)) {	
        ((GVH) holder).expand();	
      } else {	
        ((GVH) holder).collapse();	
     }
```

4. Go `com/thoughtbot/expandablerecyclerview/viewholders/GroupViewHolder.java`

Replace this line:

`listener.onGroupClick(getAdapterPosition());`

With block:

```
      if (listener.onGroupClick(getAdapterPosition())) {
        collapse();
      } else {
        expand();
     }
```

**Comment by tjwpdl** [comment]
Do you have a fix for the arrow rotations being reset after scrolling down and back up again?

**Comment by safeer-ahmed** [comment]
Its not working as expected by the changes you placed above.

**Comment by eurbon** [comment]
And is the animation arrow working when you are using just a library 'com.thoughtbot:expandablerecyclerview:1.3' ?

**Comment by safeer-ahmed** [comment]
Yes, animation is working but arrow issue is still there.

**Comment by nileshtrademonk** [comment]
Is there any prevention for arrow management.

**Comment by RiteshChandnani** [comment]
Going only with Point 4 fixes the arrow issue for me :)

**Comment by makazemi** [comment]
@eurbon : How to change Library? Its class are only readable.
