### ISSUE TITLE
Problems with saving state

### ISSUE THREAD

**Issue by DenisKapaev** [thoughtbot/expandable-recycler-view#14]
Hello and thanks for this nice library.

However there're several problems:

1) App crashes in onSaveInstanceState when it tries to cast List to ArrayList<? extends Parcelable> (Android Studio warns about unsafe cast):

`@Override
  public void onSaveInstanceState(Bundle outState) {
    outState.putParcelableArrayList(CHECKED_STATE_MAP,
        (ArrayList<? extends Parcelable>) expandableList.groups);
    super.onSaveInstanceState(outState);
  }`

I tried to fix this by changing List to ArrayList where required, but there's another problem:

2) State is not saved correctly when app is killed by Android and restored (sometimes there's blank space instead of Groups captions, sometimes children views are of incorrect type)
I tested multi-type checked recyclerview on Android 5.0.2

Cheers!

**Comment by mandybess** [comment]
hiya @DenisKapaev ! I just have a couple of questions so I can better help you, is the POJO or class in your list of items in your `ExpandableGroup` extend `Parcelable`?

**Comment by DenisKapaev** [comment]
@mandybess, I just launched the sample app
It was onSaveInstanceState in MultiTypeCheckGenreAdapter.java

**Comment by mandybess** [comment]
issue was fixed by #18 and is released
