### ISSUE TITLE
How to select only one child between all groups

### ISSUE THREAD

**Issue by lorenzoPrimi** [thoughtbot/expandable-recycler-view#140]
Hi,
I want only one child between all groups to be selected,
I tried calling clearChoices in the OnCheckChildClickListener but of course that will deselect everything after the selection, I even tried to keep in memory the old group and attr id `mBetListAdapter.checkChild(false, old_id, old_child_id);`
but also that doesn't seem to work.

Is there a way to achieve what I need?
Thanks

**Comment by TechNov** [comment]
in the ChildViewHolder class.
In the displayChild function, you can get the current item ( chil)
