### ISSUE TITLE
different layouts group and child

### ISSUE THREAD

**Issue by zipangulu** [thoughtbot/expandable-recycler-view#142]
Is there a way to obtain two different layoutmanager for groups and relative childs?
For example, i would the list of group like LinearLayoutManager (so like a simple list) but I would that opening a group, the childs that it contains are showed in a grid (so i would something like GridLayoutManager) with, for example, 2 colums..

**Comment by TrungVuHD** [comment]
Hi, I have done something similar to what you expected.

So you should have a GridLayoutManager set to your listview with this default initialization
yourGridLayoutManager = new GridLayoutManager(yourContext, 2);

then your config for that layout manager like this:
yourGridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                switch (yourAdapter.getItemViewType(position)) {
                    case ExpandableListPosition.GROUP:
                        return 2;
                    default:
                        return 1;
                }
            }
        });

**Comment by runfengai** [comment]
@TrungVuHD u sure? i tried but failed. can u write in detail.

**Comment by TrungVuHD** [comment]
Hi @runfengai ,
So when you do
new GridLayoutManager(yourContext, 2);
it means your layout is managed by a GridLayoutManager with 2 columns.
So the magic here is, you might want the group spans to fit 2 colums
If you do like this , it will act like LinearLayoutManager
`yourLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return 2;
            }
        });`

but if you check the type of item is group or child, you can do special span value for that
`yourLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                switch (mMemberTagAdapter.getItemViewType(position)) {
                    case ExpandableListPosition.GROUP:
                        return 2;
                    default:
                        return 1;
                }
            }
        });`

**Comment by pankajzanzanefidel** [comment]
hey is their any way to get child itemview position to set different layout in child of a particular parent

**Comment by alierdogan7** [comment]
> Hi @runfengai ,
> So when you do
> new GridLayoutManager(yourContext, 2);
> it means your layout is managed by a GridLayoutManager with 2 columns.
> So the magic here is, you might want the group spans to fit 2 colums
> If you do like this , it will act like LinearLayoutManager
> `yourLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() { @Override public int getSpanSize(int position) { return 2; } });`
> 
> but if you check the type of item is group or child, you can do special span value for that
> `yourLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() { @Override public int getSpanSize(int position) { switch (mMemberTagAdapter.getItemViewType(position)) { case ExpandableListPosition.GROUP: return 2; default: return 1; } } });`

You saved my life! May Allah guide you  !
