### ISSUE TITLE
Dynamically change data of view at runtime

### ISSUE THREAD

**Issue by danielRi** [thoughtbot/expandable-recycler-view#147]
It seems like when I change the 

`expandableList.groups = myNewGroups;`
`notifyDataSetChanged();`

doesnt update my listview, instead, when I start to scroll the listview suddenly updates with the new data.

`notifyDataSetChanged();`

doenst trigger 

`onBindGroupViewHolder` to be called. Is it possible to achieve this?

**Comment by whalemare** [comment]
No, it is possible only by recreating adapter, because inside lib all functionality of check expanded/collapsed group writed as closed/private api

**Comment by CsabaMiomni** [comment]
Are you serious???

**Comment by whalemare** [comment]
@CsabaMiomni i am not developer of this lib, but it works as described above

**Comment by douglasalipio** [comment]
I have the same problem. As I'm using dbflow the data is not ready at instantiating of my ExpandableGroup object so I got a null objects

**Comment by whalemare** [comment]
anyway, i remove this lib from my app and implement expandable manually. 
It is not hard, 3-4 hours
