### ISSUE TITLE
arrow's state is not maintained

### ISSUE THREAD

**Issue by tjwpdl** [thoughtbot/expandable-recycler-view#148]
When a category is opened the arrow rotates to point downward, which is important functionality.

But if you scroll down so that the category row is off the screen and then scroll back up to show it again, it resets the icon to the down position even though the category is opened.

This makes it seems like the category is closed even though it's opened.

Does anyone have a fix for this?

**Comment by mars885** [comment]
https://github.com/thoughtbot/expandable-recycler-view/issues/67#issuecomment-372026766
