### ISSUE TITLE
How do i expand an item after a network call?

### ISSUE THREAD

**Issue by gayathri-nair03** [thoughtbot/expandable-recycler-view#15]
when i click on a group item, i need to make a network call (so dont rightaway expand that group). expand the group and POPULATE subgroup items with data, only on the success callback of that network call.  is this possible?

**Comment by gayathri-nair03** [comment]
Can I set the child items, after the parent item is clicked? I need to make a n/w call each time a parent item is clicked and then populate the child items based on response. So i woulnt be able to make child items beforehand. How can i accomplish thia?

**Comment by mandybess** [comment]
The current version of the library only supports adding items via the constructor. So you cannot add items - parent or children - after the adapter has been created. Later versions of the library will definitely allow for adding groups after construction. Adding incomplete groups - i.e. only parents, without children will probably not come for a while as that would require a good amount of refactoring and is not the normal use case

**Comment by gayathri-nair03** [comment]
@mandybess - Yes, i kinda figured that out. Thanks anyway!
