### ISSUE TITLE
How to get child position when using click on child items ?

### ISSUE THREAD

**Issue by trungnguyen22** [thoughtbot/expandable-recycler-view#154]
I want to get the child item position to access the data inside child List. 
As we've already known that when using getAdapterPosition(), we can get the position of the parent's items and we can using this position to access the data inside the ArrayList that matched. 

`public class ChildComponentViewHolder extends ChildViewHolder {

        private TextView childTitle;

        public ChildComponentViewHolder(View itemView) {
            super(itemView);
            childTitle = itemView.findViewById(R.id.list_item_child_title);
            itemView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                }
            });
        }

        public void setChildTitle(String title) {
            childTitle.setText(title);
        }
    }`

**Comment by eliasbellido** [comment]
Did you get to find a way to do that?

**Comment by EvgenBES** [comment]
My class CatalogAdapter .....

And my onBindCheckChildViewHolder.............

@Override
    public void onBindCheckChildViewHolder(TechnicsTypeViewHolder holder, int flatPosition, CheckedExpandableGroup group, int childIndex) {
     
        //Click
        holder.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
           //you code 
           Log.d("TEST", "onClick: " + childIndex);
                }
            }
        });
    }
