### ISSUE TITLE
How to scroll the view?

### ISSUE THREAD

**Issue by tjwpdl** [thoughtbot/expandable-recycler-view#156]
When selecting a category I'd like everything to scroll so that the category label is at the top of the RecyclerView so that the items are shown easily.

How can I scroll the view programatically when a category is clicked?

**Comment by tjwpdl** [comment]
I've tried making a callback from expand() which calls:

linearLayoutManager.scrollToPosition(getAdapterPosition) on the RecyclerView but the views just disappear and reappear without scrolling.

**Comment by weselinka** [comment]
Have you figured out? Would be interested if so. Thanks

**Comment by tjwpdl** [comment]
No, I gave up, but I'd still like to know

**Comment by weselinka** [comment]
Well, I have found out, you should do your code here: 
![untitled](https://user-images.githubusercontent.com/20626154/47944372-76f37d00-ded1-11e8-9666-57a51ee9d39c.png)

But since I am a beginner I can not get the LinearLayout Manager there to be able to scrollToPosition.
