### ISSUE TITLE
Expanding/collapsing groups modifies child views

### ISSUE THREAD

**Issue by alex-dani** [thoughtbot/expandable-recycler-view#161]
In the child layout I have a quantity setter view. If I open the first parent and I modify the counter, then I will close the parent and open another parent, childs of the second parent will have the counter modified with the value I set in the child of the first parent. Did this happen to anyone? Any ideas how to fix this? @mandybess

**Comment by srinivasancp** [comment]
I'm also facing same issue from yesterday.. the adapter gets wrong parent/group index. Don't know how to solve this issue!
