### ISSUE TITLE
collapses all other groups when one is expanded.

### ISSUE THREAD

**Issue by joseluisng** [thoughtbot/expandable-recycler-view#163]
I have 10 groups, I open the first group and then I open the second group and the first group closes, until there all right, everything is working fine but (  when click on first group when group 10 one is expanded) I get Exceptions for Inconsistency Detected. ) or not closed the group 10, 

If the group is off the screen, it will not collapse when calling toggleGroup on it. Unless I am doing something wrong?

this code: 

 private ExpandableGroup expandedGroup;

mAdapter.setOnGroupExpandCollapseListener (new GroupExpandCollapseListener() {

            @Override
            public void onGroupExpanded(ExpandableGroup group) {
           
                if (expandedGroup != null && !expandedGroup.equals(group) && mAdapter.isGroupExpanded(expandedGroup)){
                    mAdapter.toggleGroup(expandedGroup);
                   
                }
                expandedGroup = group;
            }

            @Override
            public void onGroupCollapsed(ExpandableGroup group) {

            }
        });

against a possible solution is the nex code, that only If the group is off the screen, no closed group 

@Override public void onGroupExpanded(int positionStart, int itemCount) {
            if (itemCount > 0) {
                int groupIndex = expandableList.getUnflattenedPosition(positionStart).groupPos;
                notifyItemRangeInserted(positionStart, itemCount);
                for (ExpandableGroup grp : mGroups) {
                    if (grp != mGroups.get(groupIndex)) {
                        if (this.isGroupExpanded(grp)) {
                            this.toggleGroup(grp);
                            this.notifyDataSetChanged();
                        }
                    }
                }
            }
        }

if I remove the previous methods, when I open the groups the children have the wrong position.

**Comment by KostyaBakay** [comment]
I also have a crash and I suppose it is because of a flat position. Is there any way to do this?

**Comment by daotien0887** [comment]
In Adapter Class 
public class FAQGroupAdapter extends ExpandableRecyclerViewAdapter<FAQTitleLv1ViewHolder, FAQTitleLv2ViewHolder>

I override method:
@Override
    public void onGroupExpanded(int positionStart, int itemCount) {
        super.onGroupExpanded(positionStart, itemCount);
        for (int i = getItemCount()-1; i >= 0; i--) {
            if(i <= getItemCount()) {
                if(i != positionStart-1) {
                    if (getItemViewType(i) == GROUP && isGroupExpanded(i)) {
                        toggleGroup(i);
                    }
                }
            }
        }
    }

it working :D

**Comment by daotien0887** [comment]
GROUP is 2.
Define in file public class ExpandableListPosition

**Comment by pavelsust** [comment]
> In Adapter Class
> public class FAQGroupAdapter extends ExpandableRecyclerViewAdapter<FAQTitleLv1ViewHolder, FAQTitleLv2ViewHolder>
> 
> I override method:
> @override
> public void onGroupExpanded(int positionStart, int itemCount) {
> super.onGroupExpanded(positionStart, itemCount);
> for (int i = getItemCount()-1; i >= 0; i--) {
> if(i <= getItemCount()) {
> if(i != positionStart-1) {
> if (getItemViewType(i) == GROUP && isGroupExpanded(i)) {
> toggleGroup(i);
> }
> }
> }
> }
> }
> 
> it working :D

It works but the arrow is not working perfectly. It rotate in wrong direction now.
