### ISSUE TITLE
how to get group position from OnChildClick ?

### ISSUE THREAD

**Issue by sPhaykrew** [thoughtbot/expandable-recycler-view#168]
how to get group position from OnChildClick ?

**Comment by at-tantv** [comment]
how to get position on child click

**Comment by at-tantv** [comment]
OK done !

private fun calculateRealGroupPosition(group: ExpandableGroup<*>): Int {
        val groups = groups
        var index = -1
        for (expandableGroup in groups) {
            index ++
            if (expandableGroup == group) {
                return index
            }
        }
        return index
    }

**Comment by shijo01** [comment]
getGroups().indexOf(group);

**Comment by pranavpari** [comment]
Its not working

**Comment by hiasel** [comment]
> OK done !
> 
> private fun calculateRealGroupPosition(group: ExpandableGroup<*>): Int {
> val groups = groups
> var index = -1
> for (expandableGroup in groups) {
> index ++
> if (expandableGroup == group) {
> return index
> }
> }
> return index
> }

This works perfectly for me. Thank you

**Comment by abunayem** [comment]
> OK done !
> 
> private fun calculateRealGroupPosition(group: ExpandableGroup<*>): Int {
> val groups = groups
> var index = -1
> for (expandableGroup in groups) {
> index ++
> if (expandableGroup == group) {
> return index
> }
> }
> return index
> }

how can I do this with Java?

**Comment by abunayem** [comment]
> OK done !
> 
> private fun calculateRealGroupPosition(group: ExpandableGroup<*>): Int {
> val groups = groups
> var index = -1
> for (expandableGroup in groups) {
> index ++
> if (expandableGroup == group) {
> return index
> }
> }
> return index
> }

How can I do this with Java?
