### ISSUE TITLE
Expand All Groups

### ISSUE THREAD

**Issue by parsam10** [thoughtbot/expandable-recycler-view#175]
Hi . any body is here :) ???
how can i expand all groups by default ??
i tried toggle method but not worked .
i need a method like expandAll() or setExpand(boolean expand) for example.

**Comment by parsam10** [comment]
i founded the answer !
i wrote expandAll() method :

public void expandAll() {
        for (int i = 0; i < getItemCount(); i++) {
            if (!isGroupExpanded(i)){
                toggleGroup(i);
            }
        }
    }

and i call it after recyclerList.setAdapter() ;

**Comment by parsam10** [comment]
public void expandAll() {
        for (int i = 0; i < getItemCount(); i++) {
            if (!isGroupExpanded(i)){
                toggleGroup(i);
            }
        }
    }

**Comment by parsam10** [comment]
finally !
i founded the answer 👍 

i wrote my expandAll() method : 

public void expandAll() {
        for (int i = 0; i < getItemCount(); i++) {
            if (!isGroupExpanded(i)){
                toggleGroup(i);
            }
        }
    }

and i call that after  :
myRecyclerListView.setAdapter();

**Comment by tneginareb** [comment]
This one worked for me:

https://github.com/thoughtbot/expandable-recycler-view/issues/181#issuecomment-491491789

**Comment by tneginareb** [comment]
> finally !
> i founded the answer 👍
> 
> i wrote my expandAll() method :
> 
> public void expandAll() {
> for (int i = 0; i < getItemCount(); i++) {
> if (!isGroupExpanded(i)){
> toggleGroup(i);
> }
> }
> }
> 
> and i call that after :
> myRecyclerListView.setAdapter();

This one didn't work on my case and this worked for me:
https://github.com/thoughtbot/expandable-recycler-view/issues/181#issuecomment-491491789
