### ISSUE TITLE
I want to expand all but Expanded only first item

### ISSUE THREAD

**Issue by syeda-urooba** [thoughtbot/expandable-recycler-view#181]
val genres = getGenres()
        adapter = ParentAdapter(dockActivity, genres)
        rvBooking.layoutManager = (LinearLayoutManager(getDockActivity(), LinearLayoutManager.VERTICAL, false))
        rvBooking.adapter = adapter

/*To expand*/
        var expandableGroupList = adapter.groups
        for (i in 0 until expandableGroupList.size) {
            if (expandableGroupList[i] != null) {
                adapter.toggleGroup(expandableGroupList[i])
            }
        } 
Note: expanded only first item

**Comment by ShreyashPromact** [comment]
@syeda-urooba 
Did you get a solution to this? I am facing the same issue.

**Comment by 0x384c0** [comment]
Iterate and toggle your groups from largest group id to 0
Here example on Kotlin
```
            val adapter = ExpandableAccountsAdapter(it, layoutInflater)
            // Iterate and toggle groups
            for (i in (adapter.groups.size - 1) downTo 0) {
                if (! adapter.isGroupExpanded(i))
                    adapter.toggleGroup(i)
            }
            // Set adapter
            recyclerView.adapter = adapter
```

**Comment by syeda-urooba** [comment]
> Iterate and toggle your groups from largest group id to 0
> Here example on Kotlin
> 
> ```
>             val adapter = ParentAdapter(dockActivity, genres)
>             // Iterate and toggle groups
>             for (i in (adapter.groups.size - 1) downTo 0) {
>                 if (! adapter.isGroupExpanded(i))
>                     adapter.toggleGroup(i)
>             }
>             // Set adapter
>             recyclerView.adapter = adapter
> ```

Thats the right answer, i did the same.

**Comment by cenkgun** [comment]
> Iterate and toggle your groups from largest group id to 0
> Here example on Kotlin
> 
> ```
>             val adapter = ParentAdapter(dockActivity, genres)
>             // Iterate and toggle groups
>             for (i in (adapter.groups.size - 1) downTo 0) {
>                 if (! adapter.isGroupExpanded(i))
>                     adapter.toggleGroup(i)
>             }
>             // Set adapter
>             recyclerView.adapter = adapter
> ```

Great answer! Thank you so much @syeda-urooba
