### ISSUE TITLE
add child and title dynamically

### ISSUE THREAD

**Issue by Rahul-Surendran** [thoughtbot/expandable-recycler-view#182]
I want to add child and title dynamically on a button click.

 TitleChild titleChild1 = new TitleChild("child5");
                TitleChild titleChild2 = new TitleChild("child6");
                List<TitleChild> titleChildren1 = Arrays.asList(titleChild1,titleChild2);
                TitleParent titleParent1 = new TitleParent("title3",titleChildren1);
                titleParents = new ArrayList<>();
                titleParents.add(titleParent1);
                adapter.notifyDataSetChanged();

this code is not working

**Comment by kotvertolet** [comment]
This is known problem that notifyDataSetChanged() is not working, it's because of a bug in this library but luckily it could be fixed relatively easy, check this out for the solution: https://github.com/thoughtbot/expandable-recycler-view/issues/27#issuecomment-448226409
