### ISSUE TITLE
How to see Selected item ? 

### ISSUE THREAD

**Issue by andremachado35** [thoughtbot/expandable-recycler-view#184]
How can i see or handle the selected item of my recycle view ?

**Comment by ismailtosun** [comment]
adapter.setOnGroupClickListener(new OnGroupClickListener() {
            @Override
            public boolean onGroupClick(int flatPos) {

                Toast.makeText(getActivity(),"ClickedParentIndex : "+ String.valueOf(flatPos),Toast.LENGTH_SHORT).show();

               
                return false;
            }
        });



        adapter.setChildClickListener(new OnCheckChildClickListener() {
            @Override
            public void onCheckChildCLick(View v, boolean checked, CheckedExpandableGroup group, int childIndex) {

 

            }
        });
