### ISSUE TITLE
RecyclerView different animation when collapsing above alredy expanded groupview

### ISSUE THREAD

**Issue by nkhar** [thoughtbot/expandable-recycler-view#185]
Here is the outline of the problem: When I click on item to collapse, the item below it first draws the container then the text. However if the view below the clicked one was already expanded, it smoothly scrolls up. I don't understand why they behave differently. It might not be related to animation, but I could not think of better title. The demo in the Readme does not behave this way.

**Comment by nkhar** [comment]
Basically this was caused because in the layout RecyclerView that uses the adapter with parent and child ViewHolders, had its layout_height set to wrap_content, instead of match_parent.

**Comment by MCristoni** [comment]
Was facing this too, when collapsing or expanding it was a little bit laggy. 
Changing parents and child to match_parent worked flawlessly.
Thanks
