### ISSUE TITLE
How to persist values of edittext in childHolder when scrolling

### ISSUE THREAD

**Issue by kaysho** [thoughtbot/expandable-recycler-view#186]
I seem to lose all my data in edittext when scrolling

**Comment by yandroidUA** [comment]
I'm using this library too. I have ExpandableRecyclerView inside default RecyclerView. The issue is when i'm open one item (in ExpandableRecyclerView) and scrolling my RecyclerView that is the parent of ExpandableRecyclerView the state is loss, so after i'm scrolling back to this item it's closed.

**Comment by HoriaGoran** [comment]
you need to keep track of the group state (expanded / collapsed) and then set it back again in the onBindGroupViewHolder() method
