### ISSUE TITLE
Expandable Recyclerview inside Recycler View scrolling issue

### ISSUE THREAD

**Issue by mazmik25** [thoughtbot/expandable-recycler-view#189]
Hi thoughtbot team.
I'm currently using this library and actually it's kind of pretty helpful.
However, when i try to use this inside another recycler view, there's an issue. i cannot perform scrolling on the expandable recycler view. I also try to set my layout to 0dp or wrap_content but all of them don't work either. Can you please help me?

Current version : 1.3

**Comment by misbahazmi** [comment]
@mazmik25 - Any solution for this issue? I am also getting the same issue..
