### ISSUE TITLE
child click listener

### ISSUE THREAD

**Issue by goutomroy** [thoughtbot/expandable-recycler-view#19]
is there any child click listener?

**Comment by mandybess** [comment]
hiya @goutomroy !  yes! the `expandablecheckrecyclerview ` library has a built in listener - which you can read about [here](https://github.com/thoughtbot/expandable-recycler-view#listening-to-child-click-events). For the `expandablerecyclerview` you can add your own listener in your extension of `ChildViewHolder`

**Comment by Hitexroid** [comment]
Hi  how to set child click listener, in `expandablerecyclerview ` ?
