### ISSUE TITLE
Click animation on all child items even if clicked on ONE

### ISSUE THREAD

**Issue by bestak** [thoughtbot/expandable-recycler-view#192]
Hi guys,
when I click on one singlecheck item, all other items around inside parent get triggered and make click animation as well. I tried different things, like setting focusable or clickable false, but nothing helped yet.

Thanks for you time and help.

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
