### ISSUE TITLE
Issue with radio buttons multi-selected upon random clicks.

### ISSUE THREAD

**Issue by Ramachandran322** [thoughtbot/expandable-recycler-view#196]
Hello,

I have this library implemented to choose an option between two radio buttons. Radio buttons were created dynamically on runtime. It's working fine on my implementation.

However, when I switch between the two child radio buttons in a group, both of them were selected. This happens with all the group items.  
![radio_button](https://user-images.githubusercontent.com/50147857/58398974-38433100-8074-11e9-9881-3510a81c206b.jpg)

Please let me know how to fix this bug. By the way I am using the following library version,
implementation 'com.thoughtbot:expandablecheckrecyclerview:1.4'

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
