### ISSUE TITLE
Does not work inside Nested scrollviews

### ISSUE THREAD

**Issue by breakline87** [thoughtbot/expandable-recycler-view#198]
Height is not calculated correctly. Items get hidden if the recycleview is at the bottom of a nested scrollview

**Comment by misbahazmi** [comment]
@breakline87 - Any solution? I am also getting same issue

**Comment by breakline87** [comment]
I forgot which project I needed this but we just wrote a custom solution in the end I believe

**Comment by GitHubMurt** [comment]
I have 
```
<ScrollView>
  ...
      <androidx.recyclerview.widget.RecyclerView
                android:layout_height="wrap_content"
                android:clipToPadding="false"
                android:nestedScrollingEnabled="false"
</ScrollView
```

flag `android:nestedScrollingEnabled="false"` causes childrens of the most bottom group to be swallowed if they don't fix screen height

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
