### ISSUE TITLE
ExpandableGroup didn't have consistent setting for write and read parcelable

### ISSUE THREAD

**Issue by infinitea** [thoughtbot/expandable-recycler-view#20]
whether the item is null or not, it will all write an int into parcelable, in the read setting, only if the item is not null will call readInt, this will cause error in extended class 

  protected ExpandableGroup(Parcel in) {
    title = in.readString();
    if (in.readByte() == 0x01) {
      **int size = in.readInt();**
      items = new ArrayList<T>(size);
      Class<?> type = (Class<?>) in.readSerializable();
      in.readList(items, type.getClassLoader());
    } else {
      items = null;
    }
  }

  @Override
  public void writeToParcel(Parcel dest, int flags) {
    dest.writeString(title);
    if (items == null) {
      dest.writeByte((byte) (0x00));
      **dest.writeInt(0);**
    } else {
      dest.writeByte((byte) (0x01));
      **dest.writeInt(items.size());**
      final Class<?> objectsType = items.get(0).getClass();
      dest.writeSerializable(objectsType);
      dest.writeList(items);
    }
  }

**Comment by mandybess** [comment]
hi @infinitea thanks for catching this! Just merged a fix and will be out in the next release
