### ISSUE TITLE
When the application go to background the app closed 

### ISSUE THREAD

**Issue by Motazlubbad** [thoughtbot/expandable-recycler-view#202]
He,

I implement the library in my application, but when the application goes to background The app gives error and   EXCEPTION 

![image](https://user-images.githubusercontent.com/12714982/65149960-c7ad8f00-da2b-11e9-971e-0d5253393fb8.png)

can anyone help me?

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
