### ISSUE TITLE
how i can add imageView to expandble group?

### ISSUE THREAD

**Issue by NozimRustamov** [thoughtbot/expandable-recycler-view#204]
Hi. I have imageview in expandble group but i dont't add image resourse to holder

**Comment by MRXTAJ** [comment]
Hi. I have imageview in expandble group but i dont't add image resourse to holder

**Comment by HoriaGoran** [comment]
expandable_list_group.xml

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/selector_main_viewholder_group">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/img"
            android:layout_width="36dp"
            android:layout_height="40dp"
            android:padding="12dp"
            app:srcCompat="@drawable/ic_arrow_right_white"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/tv"
            android:layout_width="0dp"
            android:layout_height="40dp"
            android:gravity="center_vertical"
            android:textColor="@color/txtColor"
            android:textSize="18sp"
            app:layout_constraintLeft_toRightOf="@id/img"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            tools:text="bla bla" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>`

`    override fun onCreateGroupViewHolder(parent: ViewGroup, viewType: Int): MainViewHolderGroup {
        val binding = ExpandableListGroupBinding.inflate(inflater, parent, false)
        return MainViewHolderGroup(binding)
    }

    override fun onCreateChildViewHolder(parent: ViewGroup, viewType: Int): MainViewHolderChild {
        val binding = ViewholderTextDrawerBinding.inflate(inflater, parent, false)
        return MainViewHolderChild(binding, viewListener)
    }`

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
