### ISSUE TITLE
Androidx support

### ISSUE THREAD

**Issue by Parth-9711** [thoughtbot/expandable-recycler-view#205]
Does this library support androidx ?

**Comment by Mohsin92** [comment]
any status on this thread?

**Comment by tank777** [comment]
@Mohsin92  Please check my fork repo https://github.com/tank777/expandable-recycler-view
## Download
```groovy
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
ExpandableRecyclerView:
```groovy
implementation 'com.github.tank777.expandable-recycler-view:expandablerecyclerview:1.6@aar'
```

ExpandableCheckRecyclerView:
```groovy
implementation 'com.github.tank777.expandable-recycler-view:expandablecheckrecyclerview:1.6@aar'
```

**Comment by bpappin** [comment]
+1

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
