### ISSUE TITLE
Scroll to specefic child position 

### ISSUE THREAD

**Issue by maksimiuk** [thoughtbot/expandable-recycler-view#207]
Hello. How can I scroll to specific child position?

**Comment by sheckspir** [comment]
As I see, there is no special method for that logic
I think we can resolve it by adding a special method in the adapter
```
fun getGroupItemRealPosition(indexGroup: Int) : Int {
        var group = 0
        for (i in 0..itemCount) {
            if (getItemViewType(i) == ExpandableListPosition.GROUP) {
                group++
            }
            if (group > indexGroup) {
                return i
            }
        }
        return -1
    }
```
Use the result of that method to scroll to position by RecyclerView.scrollToPosition

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
