### ISSUE TITLE
How to add delete on swipe to childviewitem.I am not able to get the position of child and parent item in my Fragment.Please help

### ISSUE THREAD

**Issue by Anushree278** [thoughtbot/expandable-recycler-view#209]
I am trying to get the position of child and parent item in my Fragment to delete items from list

**Comment by Anushree278** [comment]
I am trying to get the position of child and parent item in my Fragment to delete items from list

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
