### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by mraza83** [thoughtbot/expandable-recycler-view#21]
I have an expandable view in which I have a rotation animation similar to the code samples.  On group/parent views which have few child items, there is no problem.  When there are larger number of child items (i.e. 39 children in my case), the arrow animation on expanding the group is slow and jumps states.  When collapsing, the animation is smooth.

**Comment by Corical** [comment]
Issue seems to be not calling `notifyDataSetChanged()` from `runOnUiThread` when changes were made.
