### ISSUE TITLE
Is it possible to put single and multiple check items in one recyclerview?

### ISSUE THREAD

**Issue by ddpatel2606** [thoughtbot/expandable-recycler-view#213]
Hello I want to develop this kind of functionality.

In which I can select single and multiple in one recycler view. Please see attached screen shot.

Please help me I want this asap.

![dd](https://user-images.githubusercontent.com/4408862/88529819-236a8080-d01e-11ea-98ca-6ab993b0a740.png)

Thanks

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
