### ISSUE TITLE
Display the same background for Childs

### ISSUE THREAD

**Issue by jesustrejo10** [thoughtbot/expandable-recycler-view#214]
Ex: If my parent holder is a card view and I want to display the Childs inside that card view, is there any way to do it through this library?

could be a card view or a shape, basically what I'd like to archive is keep the parent and Childs in the same layout or container.

Please let me know if you need more information

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
