### ISSUE TITLE
How to use it with Paging 

### ISSUE THREAD

**Issue by jDilshodbek** [thoughtbot/expandable-recycler-view#217]
How Can I use this library with paging library. It generally requires adapter to be extended from PagedListAdapter

**Comment by safeer-ahmed** [comment]
Is there any clue for this to be used with Paging3, or anybody knows any alternative to it?

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
