### ISSUE TITLE
Tried to use preview panel provider (JavaFX WebView), but it is unavailable. Reverting to default

### ISSUE THREAD

**Issue by DroidDevRis** [thoughtbot/expandable-recycler-view#218]
**Not able to set up application on latest version
found msg.
Tried to use preview panel provider (JavaFX WebView), but it is unavailable. Reverting to default

After moving further project not imported successfully.**

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
