### ISSUE TITLE
There is a `toggleGroup` function which will expand a group if it is collapsed

### ISSUE THREAD

**Issue by Rozhan92** [thoughtbot/expandable-recycler-view#219]
There is a `toggleGroup` function which will expand a group if it is collapsed

_Originally posted by @mandybess in https://github.com/thoughtbot/expandable-recycler-view/issues/32#issuecomment-271672993_

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
