### ISSUE TITLE
NotifyItemChanged does not call onBindChildViewHolder

### ISSUE THREAD

**Issue by suku-h** [thoughtbot/expandable-recycler-view#22]
I am clicking an item (child), opens a dialog fragment. If CANCEL is pressed then nothing happens and if OK is pressed then the background color of the childview changes.

This is notified through `notifyItemChanged()`. If the group is collapsed and expanded again then the data change gets reflect but it does not get reflected if the group remains expanded.

For the change to be reflected immediately I have tried the following 
1.  `DefaultItemAnimator animator = new DefaultItemAnimator() {
            @Override
            public boolean canReuseUpdatedViewHolder(RecyclerView.ViewHolder viewHolder) {
                return true;
            }
        };
        rvFoodList.setItemAnimator(animator);`

2. `((DefaultItemAnimator) rvFoodList.getItemAnimator()).setSupportsChangeAnimations(false);`

3. `rvFoodList.setItemAnimator(null);`

4. `((SimpleItemAnimator) rvFoodList.getItemAnimator()).setSupportsChangeAnimations(true);`

None of these work.

Please tell how can I achieve this?

**Comment by Rogdan** [comment]
== Solution for MultiTypeExpandableRecyclerViewAdapter ==
The decition is very simple, but hard to find:)
in "notify item changed" you must pass not "absolutItemPosition", but "FlatItemPosition".
so, to find flat position of child, you must call in adapter:

`int flatChildPos = expandableList.getFlattenedChildIndex(groupPos, posInGroup);
notifyItemChanged(flatChildPos );
`

from documentation:

> The flat position (or index in the list of {@link#getVisibleItemCount()} in the list at which to bind

So, it is index in visible items list
