### ISSUE TITLE
Strange Behavior on Dynamic Group Header Size

### ISSUE THREAD

**Issue by khrlimam** [thoughtbot/expandable-recycler-view#225]
I have a case when the count of group header is changed dynamically based on new data. Everything is fine for fixed sized group header (I assume), the app is crashes when previously group header count is smaller then the new group header it throws IndexOutOfBoundsException. But when the previous data has group header bigger then the new data, no crash. I find this is strange.

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
