### ISSUE TITLE
When app not used for a while, expandablerecyclerview menus are empty

### ISSUE THREAD

**Issue by thomfriedel** [thoughtbot/expandable-recycler-view#230]
I have been using expandable recyclerview for years but a problem I've had for some time is now very frequent.  If the application is not used for a while (it used to be days, but now it can be hours), every activity that uses expandablerecyclerview will be blank.  I have to hit home twice to get to the splash page when everything starts to work again.   There is nothing special about the splash page and nothing to do with expandablerecyclerview there.
          
I think it is odd that it happens to all activities that use it, and not just one.  I presume some resource is getting destroyed or recycled, and this is confusing something somewhere.  The database still works so the recyclerview lists should be intact.  I don't know how to approach this problem as I haven't seen it in the debugger.
        
My apps are free, and no one has complained about the problem, but it really bothers me and I would be happy to pay a little if someone can help me fix it.

**Comment by Rdevs** [comment]
+1

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
