### ISSUE TITLE
Expand and collapse smoothly 

### ISSUE THREAD

**Issue by liguopengbenli** [thoughtbot/expandable-recycler-view#231]
Is there a way to expand list and collapse smoothly with animation?

I can't find a way to define a animation.

**Comment by Rdevs** [comment]
@Override
            public void expand() {
                animateExpand();
            }

            @Override
            public void collapse() {
                animateCollapse();
            }

            private void animateExpand() {
                ObjectAnimator animation = ObjectAnimator.ofFloat(ivArrowIcon, "rotation", 90f);
                animation.setDuration(300);
                animation.start();
            }

            private void animateCollapse() {
                ObjectAnimator animation = ObjectAnimator.ofFloat(ivArrowIcon, "rotation", 0f);
                animation.setDuration(300);
                animation.start();
            }
            
            Override the expand and collapse methods and call the above methods `animateExpand`()  and `animateCollapse`()
            `ivArrowIcon` is the arrow icon that will rotate according to collapse or expand behavior.

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
