### ISSUE TITLE
Error dowloading library

### ISSUE THREAD

**Issue by alvarosanchezduran** [thoughtbot/expandable-recycler-view#233]
When i try to compile my android app i have this error:

Could not find com.thoughtbot:expandablecheckrecyclerview:1.4.

I am adding the library like this: 
implementation 'com.thoughtbot:expandablecheckrecyclerview:1.4'

And in the repositories I have added both mavenCentral and jcenter

**Comment by DroznykD** [comment]
Have the same problem with both check and 'base' version
Also coudn't get com.theartofdev.edmodo:android-image-cropper:2.8.0. but it can be replaced, maybe there is some sort of availability issue on maven repo side

**Comment by vjysrgr** [comment]
@alvarosanchezduran @DroznykD 
any solution ??

**Comment by dangalasko** [comment]
Looks like its been removed from maven https://mvnrepository.com/artifact/com.thoughtbot/expandablecheckrecyclerview?repo=jcenter only version 1 is there

**Comment by 3llomi** [comment]
You can download it from Jitpack #227

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
