### ISSUE TITLE
Unable to add lib in new created project (Android Studio Giraffe | 2022.3.1)

### ISSUE THREAD

**Issue by Dalvendra** [thoughtbot/expandable-recycler-view#234]
While adding your lib getting below error, Please suggest me the solution 

Failed to resolve: com.thoughtbot:expandablerecyclerview:1.3
Show in Project Structure dialog
Affected Modules: app

<img width="757" alt="image" src="https://github.com/thoughtbot/expandable-recycler-view/assets/19201738/5e86a662-41a4-4244-9f1b-99e35a7330e9">

**Comment by musabagab** [comment]
Same issue here,
Any solutions ?

**Comment by vjysrgr** [comment]
> Same issue here, Any solutions ?

found any solution??

**Comment by dangalasko** [comment]
`implementation 'com.github.thoughtbot:expandable-recycler-view:1.4'`

Pull it directly from Github

**Comment by sajid-gohar** [comment]
@dgalasko-godaddy i pull it directly but still same issue any work around...?

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235
