### ISSUE TITLE
Examples with the XML layout files

### ISSUE THREAD

**Issue by murparreira** [thoughtbot/expandable-recycler-view#24]
Hello, the documentation is great for the Java part of the library. Can you provide the layout files in the docs too? 
The `genre_title`, `artist_name`, `list_item_genre`, `list_item_artist` and `recycler_view`.
How does one talk to the other?
Or if there's another source of documentation with a full look at what the code looks like, can you point me in that direction?

Much appreciated.

**Comment by mandybess** [comment]
hi @murparreira ! The layout files, and all the code from the README can all be found in the sample code ([here](https://github.com/thoughtbot/expandable-recycler-view/tree/master/sample/))
