### ISSUE TITLE
Reload expandable-recycler-view

### ISSUE THREAD

**Issue by DanhDue** [thoughtbot/expandable-recycler-view#27]
Hi. Thank for great library!
I implement this expandable-recycler-view for my project, but I don't know how to reload data for it.

You can write a tutorial or  sample code?

Thank so much!

**Comment by Inbridge04** [comment]
Hi, I do have same question. I tried to implement `SwipeRefreshLayout` with your library but I can not. Help us bro!

**Comment by mandybess** [comment]
Hi, the library does not currently allow for refreshing the data with the existing adapter. That is a definitely a feature we want to add down the line

**Comment by Inbridge04** [comment]
Hi, thanks for your valuable reply. I'm waiting.

**Comment by sudhanshunathmishra** [comment]
Hi,

One solution towards this is creating a new adapter every time I have new pieces of data. Are there any other solutions you would recommend?

**Comment by giusha** [comment]
Even when I create new adapter, some of the groups are not expanding. I checked items and they are populated. I'm using recyclerview's method swapadapter: recyclerView.swapAdapter(catalogAdapter, true);
to change adapter, but as I said some of the groups are not expanding. Did anybody found a solution?

**Comment by ericmguimaraes** [comment]
I think it would be good to add this limitation to the readme file, I just lost some time to make it work with this library to only then learn about that limitation.

**Comment by ericmguimaraes** [comment]
Although, I could use a workaround recreating the layout manager and the adapter. It is not so performatic but is did the trick for me.

**Comment by giusha** [comment]
How did you recreate layout manager? I created new adapter and changed the old one with swapAdapter method and it worked partly, as I said some groups are not expanding. So Can you say what did you do in detail to work around this issue?

**Comment by Lihacovs** [comment]
Is it possible save the state of adapter if i recreate it to update the data? Or does anybody made workaround solution to populate adapter's data dynamically without recreating it?

**Comment by kafukwen** [comment]
I think there is not some enhancement :(

**Comment by oec08** [comment]
@ericmguimaraes Hey do you have a code sample available that shows how you recreated the layout manager and adapter. I just learned of this limitation as well

**Comment by davehofmann** [comment]
I found a way to reload the expandable recycler view. The trick is to save the expand/collapsed states in a `Bundle`:

```
Bundle bundle = new Bundle();
oldAdapter.onSaveInstanceState(bundle); // save expand/collapsed states
recyclerView.setAdapter(...) // set a new adapter to show model changes
newAdapter.onRestoreInstanceState(bundle); // restore expand/collapsed states in the new adapter
```

**Comment by DmitryBrenvald** [comment]
The problem is in constructor in a class com.thoughtbot.expandablerecyclerview.models.ExpandableList.
```
  public ExpandableList(List<? extends ExpandableGroup> groups) {
    this.groups = groups;

    expandedGroupIndexes = new boolean[groups.size()];
    for (int i = 0; i < groups.size(); i++) {
      expandedGroupIndexes[i] = false;
    }
  }
```
As you can see there are two lists of data.
You can change "groups" but you can't change "expandedGroupIndexes".
The field "expandedGroupIndexes" has a public access, but instance of this class has protected access. (in com.thoughtbot.expandablerecyclerview.ExpandableRecyclerViewAdapter class)
A solution is:
1. Create a package com.thoughtbot.expandablerecyclerview in your project.
2. Create a class in this package, for example ExpandableListUtils
3. Create a method for update the field "expandedGroupIndexes"

```
package com.thoughtbot.expandablerecyclerview;

public class ExpandableListUtils {

    public static void notifyGroupDataChanged(ExpandableRecyclerViewAdapter adapter) {
        adapter.expandableList.expandedGroupIndexes = new boolean[adapter.getGroups().size()];
        for (int i = 0; i < adapter.getGroups().size(); i++) {
            adapter.expandableList.expandedGroupIndexes[i] = false;
        }
    }
}

```
4. Call this method in your adapter, before you call notifyDataSetChanged();

```
    public void addAll(List<GroupItem> groups) {
        ((List<GroupItem>)getGroups()).addAll(groups);
        ExpandableListUtils.notifyGroupDataChanged(this);
        notifyDataSetChanged();
    }
```

**Comment by fantasy1022** [comment]
The method from DmitryBrenvald works for me.
It should merge to source code!

**Comment by engr-erum** [comment]
> The method from DmitryBrenvald works for me.
> It should merge to source code!

Hi, @fantasy1022  can you pls point me towards right direction.
How u resolve issue ? 
Please share exact code logic to handle this?

**Comment by kotvertolet** [comment]
Actually there is even better solution than the provided one by DmitryBrenvald - you just have to simply extend the ExpandableRecyclerViewAdapter with your own custom class and then add previously mentioned notifyGroupDataChanged() method. It will be something like this:
```
public abstract class CustomExpandableRecyclerViewAdapter<GVH extends GroupViewHolder, CVH extends ChildViewHolder> extends ExpandableRecyclerViewAdapter<GVH, CVH> {

    public CustomExpandableRecyclerViewAdapter(List<? extends ExpandableGroup> groups) {
        super(groups);
    }

    public void notifyGroupDataChanged() {
        expandableList.expandedGroupIndexes = new boolean[getGroups().size()];
        for (int i = 0; i < getGroups().size(); i++) {
            expandableList.expandedGroupIndexes[i] = false;
        }
    }
}
```
Then make your adapter class extend CustomExpandableRecyclerViewAdapter instead of ExpandableRecyclerViewAdapter and now in order to update the data in the recycler view you have to do like DmitryBrenvald said:

> Call this method in your adapter, before you call notifyDataSetChanged();
>    ```
>  public void addAll(List<GroupItem> groups) {
>         ((List<GroupItem>)getGroups()).addAll(groups);
>         notifyGroupDataChanged();
>         notifyDataSetChanged();
>     }
> ```

**Comment by alpeshrathod25** [comment]
> Actually there is even better solution than the provided one by DmitryBrenvald - you just have to simply extend the ExpandableRecyclerViewAdapter with your own custom class and then add previously mentioned notifyGroupDataChanged() method. It will be something like this:
> 
> ```
> public abstract class CustomExpandableRecyclerViewAdapter<GVH extends GroupViewHolder, CVH extends ChildViewHolder> extends ExpandableRecyclerViewAdapter<GVH, CVH> {
> 
>     public CustomExpandableRecyclerViewAdapter(List<? extends ExpandableGroup> groups) {
>         super(groups);
>     }
> 
>     public void notifyGroupDataChanged() {
>         expandableList.expandedGroupIndexes = new boolean[getGroups().size()];
>         for (int i = 0; i < getGroups().size(); i++) {
>             expandableList.expandedGroupIndexes[i] = false;
>         }
>     }
> }
> ```
> 
> Then make your adapter class extend CustomExpandableRecyclerViewAdapter instead of ExpandableRecyclerViewAdapter and now in order to update the data in the recycler view you have to do like DmitryBrenvald said:
> 
> > Call this method in your adapter, before you call notifyDataSetChanged();
> > ```
> > public void addAll(List<GroupItem> groups) {
> >      ((List<GroupItem>)getGroups()).addAll(groups);
> >      notifyGroupDataChanged();
> >      notifyDataSetChanged();
> >  }
> > ```



> The problem is in constructor in a class com.thoughtbot.expandablerecyclerview.models.ExpandableList.
> 
> ```
>   public ExpandableList(List<? extends ExpandableGroup> groups) {
>     this.groups = groups;
> 
>     expandedGroupIndexes = new boolean[groups.size()];
>     for (int i = 0; i < groups.size(); i++) {
>       expandedGroupIndexes[i] = false;
>     }
>   }
> ```
> 
> As you can see there are two lists of data.
> You can change "groups" but you can't change "expandedGroupIndexes".
> The field "expandedGroupIndexes" has a public access, but instance of this class has protected access. (in com.thoughtbot.expandablerecyclerview.ExpandableRecyclerViewAdapter class)
> A solution is:
> 
> 1. Create a package com.thoughtbot.expandablerecyclerview in your project.
> 2. Create a class in this package, for example ExpandableListUtils
> 3. Create a method for update the field "expandedGroupIndexes"
> 
> ```
> package com.thoughtbot.expandablerecyclerview;
> 
> public class ExpandableListUtils {
> 
>     public static void notifyGroupDataChanged(ExpandableRecyclerViewAdapter adapter) {
>         adapter.expandableList.expandedGroupIndexes = new boolean[adapter.getGroups().size()];
>         for (int i = 0; i < adapter.getGroups().size(); i++) {
>             adapter.expandableList.expandedGroupIndexes[i] = false;
>         }
>     }
> }
> ```
> 
> 1. Call this method in your adapter, before you call notifyDataSetChanged();
> 
> ```
>     public void addAll(List<GroupItem> groups) {
>         ((List<GroupItem>)getGroups()).addAll(groups);
>         ExpandableListUtils.notifyGroupDataChanged(this);
>         notifyDataSetChanged();
>     }
> ```

With this solution items are flicking when we have large amount of items bind to the recyelverview .

**Comment by alpeshrathod25** [comment]
> > Actually there is even better solution than the provided one by DmitryBrenvald - you just have to simply extend the ExpandableRecyclerViewAdapter with your own custom class and then add previously mentioned notifyGroupDataChanged() method. It will be something like this:
> > ```
> > public abstract class CustomExpandableRecyclerViewAdapter<GVH extends GroupViewHolder, CVH extends ChildViewHolder> extends ExpandableRecyclerViewAdapter<GVH, CVH> {
> > 
> >     public CustomExpandableRecyclerViewAdapter(List<? extends ExpandableGroup> groups) {
> >         super(groups);
> >     }
> > 
> >     public void notifyGroupDataChanged() {
> >         expandableList.expandedGroupIndexes = new boolean[getGroups().size()];
> >         for (int i = 0; i < getGroups().size(); i++) {
> >             expandableList.expandedGroupIndexes[i] = false;
> >         }
> >     }
> > }
> > ```
> > 
> > 
> > Then make your adapter class extend CustomExpandableRecyclerViewAdapter instead of ExpandableRecyclerViewAdapter and now in order to update the data in the recycler view you have to do like DmitryBrenvald said:
> > > Call this method in your adapter, before you call notifyDataSetChanged();
> > > ```
> > > public void addAll(List<GroupItem> groups) {
> > >      ((List<GroupItem>)getGroups()).addAll(groups);
> > >      notifyGroupDataChanged();
> > >      notifyDataSetChanged();
> > >  }
> > > ```
> 
> > The problem is in constructor in a class com.thoughtbot.expandablerecyclerview.models.ExpandableList.
> > ```
> >   public ExpandableList(List<? extends ExpandableGroup> groups) {
> >     this.groups = groups;
> > 
> >     expandedGroupIndexes = new boolean[groups.size()];
> >     for (int i = 0; i < groups.size(); i++) {
> >       expandedGroupIndexes[i] = false;
> >     }
> >   }
> > ```
> > 
> > 
> > As you can see there are two lists of data.
> > You can change "groups" but you can't change "expandedGroupIndexes".
> > The field "expandedGroupIndexes" has a public access, but instance of this class has protected access. (in com.thoughtbot.expandablerecyclerview.ExpandableRecyclerViewAdapter class)
> > A solution is:
> > 
> > 1. Create a package com.thoughtbot.expandablerecyclerview in your project.
> > 2. Create a class in this package, for example ExpandableListUtils
> > 3. Create a method for update the field "expandedGroupIndexes"
> > 
> > ```
> > package com.thoughtbot.expandablerecyclerview;
> > 
> > public class ExpandableListUtils {
> > 
> >     public static void notifyGroupDataChanged(ExpandableRecyclerViewAdapter adapter) {
> >         adapter.expandableList.expandedGroupIndexes = new boolean[adapter.getGroups().size()];
> >         for (int i = 0; i < adapter.getGroups().size(); i++) {
> >             adapter.expandableList.expandedGroupIndexes[i] = false;
> >         }
> >     }
> > }
> > ```
> > 
> > 
> > 
> > 1. Call this method in your adapter, before you call notifyDataSetChanged();
> > 
> > ```
> >     public void addAll(List<GroupItem> groups) {
> >         ((List<GroupItem>)getGroups()).addAll(groups);
> >         ExpandableListUtils.notifyGroupDataChanged(this);
> >         notifyDataSetChanged();
> >     }
> > ```
> 
> With this solution items are flicking when we have large amount of items in recyelverview . Can any one have idea how to avoid this behaviour?

**Comment by dgthang97** [comment]
```java

public void collapseAll() {
        int groupSize = groupList.size();
        for (int i = 0; i < groupSize; i++) {
            expandableItemManager.collapseGroup(i);
        }
    }

```
It working for me.
