### ISSUE TITLE
Is there a way to make one group expanded by default?

### ISSUE THREAD

**Issue by dotocan** [thoughtbot/expandable-recycler-view#3]
Let's say I have 3 groups and I want the first one to already be expanded when I open the app.

**Comment by mlorenz2** [comment]
Hi,
I would really appreciate if this would be possible.

**Comment by mandybess** [comment]
@dotocan you can programmatically expand a group by calling `adapter.toggleGroup(1);` - or whatever the flat list position of the group you want expanded is. 

If you call `toggleGroup()` before you set the adapter to the `RecyclerView` it will appear expanded immediately on inflation. For example: 

```java
    adapter = new BandAdapter(makeBands());
    adapter.toggleGroup(1);
    recyclerView.setLayoutManager(layoutManager);
    recyclerView.setAdapter(adapter);
```
