### ISSUE TITLE
Expand a group programmatically 

### ISSUE THREAD

**Issue by a9595** [thoughtbot/expandable-recycler-view#32]
How can I expand a group programmatically?

For example I have 3 groups. And when user opens an activity - the groups should be expanded already (without making user to expand each group manually).

Maybe something like:
`recyclerView.getGroup(1).expand()`

p.s. Thanks for this great lib guys!

**Comment by mandybess** [comment]
There is a `toggleGroup` function which will expand a group if it is collapsed
