### ISSUE TITLE
Code only works with CheckedTextView by default

### ISSUE THREAD

**Issue by philipgiuliani** [thoughtbot/expandable-recycler-view#36]
Hi,

I just spent a while to find out why my code was not working and noticed that `CheckedTextView` is hardcoded.

https://github.com/thoughtbot/expandable-recycler-view/blob/5c7e78f7ad933f4f2ed45fb87c7a2b5c41d098d3/expandablecheckrecyclerview/src/main/java/com/thoughtbot/expandablecheckrecyclerview/viewholders/CheckableChildViewHolder.java#L39

Every `Checkable` should implement `toggle()`. So why is this hardcoded?

**Comment by ahmedkhan23** [comment]
- I ran into the same issue and pinpointed the same issue -> hopefully a quick fix can be in place

**Comment by mandybess** [comment]
fixed in #40
