### ISSUE TITLE
notifyDataSetChanged() not working

### ISSUE THREAD

**Issue by danponce** [thoughtbot/expandable-recycler-view#39]
Tried this method on the adapter and got an exception. I just add a new Genre to the simple expand sample app.

**Comment by sudhanshunathmishra** [comment]
I am getting the same error. Every time I adding or deleting an object to/from the underlying list, it crashes with " java.lang.ArrayIndexOutOfBoundsException: length=1; index=1" in ExpandableList.numberOfVisibleItemsInGroup

**Comment by mandybess** [comment]
The current version of the library does not support adding / removing items from list of `ExpandableGroup` that you instantiated the adapter with. 

We hope to have this feature out in the next relase

**Comment by mandybess** [comment]
Duplicate of #27
