### ISSUE TITLE
Make an interface for ExpandableGroup

### ISSUE THREAD

**Issue by bytehala** [thoughtbot/expandable-recycler-view#41]
Maybe have IExpandableGroup that is an interface which has exact contract that ExpandableGroup has.

This would allow developers to decide what their "Group" model extends from.

In my case, I need to extend BaseModel from dbFlow. I mean, of course I can create a wrapper class that contains my model and extends ExpandableGroup, but then I'm not sure that would even be compatible with my existing client code so a lot of classes might have to adapt.

By having IExpandableGroup, I just have to implement it in my existing model class and respect its contract.

ExpandableGroup can continue being the base class that people can use.

Yes, I know that's asking a lot.. Besides, I see some classes having to change when implementing this request, for example ExpandableRecyclerViewAdapter.onBindChildViewHolder(). It's a breaking change for sure.

**Comment by 1amGr00t** [comment]
Yes! Or make the ExpandableGroup members protected giving the developer more control over how to instantiate a Group Item !

**Comment by mkrupal09** [comment]
any update on this?
