### ISSUE TITLE
Is there a method to expand a group programmatically? 

### ISSUE THREAD

**Issue by sudhanshunathmishra** [thoughtbot/expandable-recycler-view#43]

**Comment by rajsuvariya** [comment]
Yes.

You can write this line to expand group programmatically
adapter.onGroupClick(position);

**Comment by pauliktamas** [comment]
Hello,

If I have 3 groups with multiple children, and I call the method mentioned above I get a weird result. I attached a GroupExpandCollapseListener and as I iterate through the 3 groups and call onGroupClick on each of them, the listener callbacks are like the following:
1. onGroupExpanded on the first group
2. onGroupCollapsed on the first group
3. onGroupExpanded on the third group

and the end result is that I have the third group opened but the other two are closed. Am I doing something wrong?

        categoryAdapter.setOnGroupExpandCollapseListener(new GroupExpandCollapseListener() {
            @Override
            public void onGroupExpanded(ExpandableGroup group) {
                Log.d(TAG, group.getTitle() + " opened.");
            }

            @Override
            public void onGroupCollapsed(ExpandableGroup group) {
                Log.d(TAG, group.getTitle() + " closed.");
            }
        });

        for (int i = 0; i < categoryAdapter.getGroups().size(); i++) {
            categoryAdapter.onGroupClick(i);
        }

What I want to achieve is that all the 3 groups are opened, and all the child elements have the checkboxes set (as its used for default filter options).

Thanks in advance!

**Comment by rajsuvariya** [comment]
public void expandGroup (int gPos){
   if(adapter.isGroupExpanded(gPos)){
     return;
   }
   adapter.toggleGroup(gPos);
 }

 public void collpaseGroup (int gPos){
   if(!adapter.isGroupExpanded(gPos)){
     return;
   }
   adapter.toggleGroup(gPos);
 }

use these methods to expand more than one group at a time programatically.

**Comment by pauliktamas** [comment]
Tried it, still the same issue. I found out what is causing it tho. I have 3 groups - closed. If I toggle the first group to open it (item #0), the next group's ID will change from #1 to #3 as the first group had 2 child elements.

This means, that the adapter.toggleGroup(pos) method calls toggle on child elements too, not just group elements which is not what I expected.

**Comment by rajsuvariya** [comment]
Yes sorry, It is because toggleGroup takes the flat position.

Just for your purpose you can use
for (int i = categoryAdapter.getGroups().size()-1; i >=0 ; i--) {
       expandGroup(i);
}

**Comment by mandybess** [comment]
Hi!

There are two methods for toggling a group. [One](https://github.com/thoughtbot/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/thoughtbot/expandablerecyclerview/ExpandableRecyclerViewAdapter.java#L185) takes the flat list position as a parameter and [the other ](https://github.com/thoughtbot/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/thoughtbot/expandablerecyclerview/ExpandableRecyclerViewAdapter.java#L185)takes the `ExpandableGroup` as a parameter.
