### ISSUE TITLE
MultiTypeExpandableRecyclerView

### ISSUE THREAD

**Issue by milis92** [thoughtbot/expandable-recycler-view#49]
Is it possible to have SingleCheckExpandableGroup and MultiCheckExpandableGroup in same adapter?
Iw tried using MultiTypeExpandableRecyclerViewAdapter but single checkable groups are not working(im able to check all of the items)

**Comment by Squacco** [comment]
Did you find any solution? Even I am facing this issue

**Comment by ddpatel2606** [comment]
Hi bro Did you find any solution ?
