### ISSUE TITLE
Multiple Parent View Types + MultiTypeExpandableRecyclerViewAdapter

### ISSUE THREAD

**Issue by yitz-grocerkey** [thoughtbot/expandable-recycler-view#5]
When combining these two features the checked positions change unpredictably. I assume it is because for example, lets say that group viewholder of type A stores the information about the children's checked status, but then viewholder of type B doesn't have that information.

**Comment by mandybess** [comment]
Hiya @yitz-grocerkey ! The two features you listed do not include checking :( Assuming you meant multiple group view types via a `MultiTypeExpandableRecyclerViewAdapter` with checkable children, I can tell you that group view holders do not hold any information about the state of the children. The `ExpandableGroup` and `CheckedExpandableGroup` maintain the state. 

Without seeing your code I can't really tell you exactly what's going on - so I added a [sample](https://github.com/thoughtbot/expandable-recycler-view/commit/5c7e78f7ad933f4f2ed45fb87c7a2b5c41d098d3) - using `MultiTypeExpandableRecyclerViewAdapter` and the `ChildCheckController` to show how to implement multiple group types with single check children. You could obviously change out the single check to be multicheck. 

Hopefully this helps!

xx
