### ISSUE TITLE
how to set click event of  child of any group 

### ISSUE THREAD

**Issue by hirenpatel868** [thoughtbot/expandable-recycler-view#51]
****

**Comment by rajsuvariya** [comment]
You can set on click in child view holder class
itemview.setonclicklistner();

**Comment by traifdevelopment** [comment]
That doesn't work for me. In view i cant do setOnclick.
Well, I can, but doesn't respond. When I put in TextView, work perfectly.

Can someone help me?

**Comment by rajsuvariya** [comment]
Can you share your code?

**Comment by traifdevelopment** [comment]
Of course.

**XML:**
`<?xml version="1.0" encoding="utf-8" ?>
<android.support.v7.widget.CardView
    android:layout_width="match_parent"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    card_view:cardCornerRadius="0dp"
    android:layout_height="wrap_content">

            <LinearLayout
                android:orientation="vertical"
                android:layout_width="match_parent"
                android:id="@+id/line"
                android:clickable="true"
                android:layout_height="wrap_content">

                <LinearLayout
                    android:background="#ffffff"
                    android:orientation="horizontal"
                    android:clickable="true"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    
                    <ImageView
                        android:id="@+id/image"
                        android:layout_width="@dimen/perfil_image_size"
                        android:layout_height="@dimen/perfil_image_size"
                        android:layout_marginLeft="15dp"
                        android:layout_marginTop="15dp"
                        android:layout_marginBottom="15dp"
                        android:layout_gravity="center_vertical" />
                    <LinearLayout
                        android:orientation="vertical"
                        android:layout_width="match_parent"
                        android:layout_marginBottom="15dp"
                        android:clickable="true"
                        android:layout_height="wrap_content">
                        <TextView
                            android:id="@+id/name"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="name"
                            android:maxEms="12"
                            android:singleLine="false"
                            android:layout_marginLeft="15dp"
                            android:textColor="@android:color/black"
                            android:textSize="16sp"
                            android:layout_marginTop="15dp" />
                        <TextView
                            android:id="@+id/time"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="time"
                            android:layout_marginLeft="15dp"
                            android:textColor="@android:color/black"
                            android:textSize="14sp"
                            android:layout_marginTop="5dp" />
                    </LinearLayout>
                    <ImageView
                        android:text="Button"
                        android:layout_gravity="right"
                        android:src="@drawable/ic_keyboard_arrow_right_black_48px"
                        android:layout_marginRight="10dp"
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:id="@+id/imageView" />
                </LinearLayout>


            </LinearLayout>


        <View
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_gravity="bottom"
            android:background="@android:color/darker_gray"/>


    </android.support.v7.widget.CardView>

`

**ADAPTER:** 
`public class ExpandableAdapter extends ExpandableRecyclerViewAdapter<GroupViewHolder, CViewHolder> {
    Context c;
    LayoutInflater mInflater;
    public ExpandableAdapter(List<? extends ExpandableGroup> groups, Context) {
        super(groups);
        this.c = c;
        mInflater = LayoutInflater.from(c);
    }

    @Override
    public GroupViewHolder onCreateGroupViewHolder(ViewGroup parent, int viewType) {
        View view = mInflater.inflate(R.layout.layout_group, parent, false);
        return new GroupViewHolder(view);
    }

    @Override
    public ChildViewHolder onCreateChildViewHolder(ViewGroup parent, int viewType) {
        View view = mInflater.inflate(R.layout.layout_child, parent, false);
        return new CViewHolder(view, c);
    }

    @Override
    public void onBindChildViewHolder(CViewHolderholder, int flatPosition, ExpandableGroup group, int childIndex) {
        final Person objeto = ((Person) group.getItems().get(childIndex));
        holder.onBind(objeto, group.getTitle());

    

    @Override
    public void onBindGroupViewHolder(GroupViewHolder holder, int flatPosition, ExpandableGroup group) {
        holder.setGenreTitle(group);
    }

`

**ChildViewHolder:**
`
public class CViewHolder extends ChildViewHolder {

    public TextView name, time, cantidad;
    public ImageView image;
    Context context;
    View itemView;



    public CViewHolder(final View itemView, final Context context) {
        super(itemView);

        this.itemView = itemView;
        this.itemView.setClickable(true);

		 itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                System.out.println("HAHA");
            }
        });


        this.context = context;
        name = (TextView) itemView.findViewById(R.id.name);
        time = (TextView)itemView.findViewById(R.id.time);
        image = (ImageView) itemView.findViewById(R.id.image);

        image.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
				System.out.println("HAHA");
            }
        });
    }

    public void onBind(final Person persona, final String horarioComida) {
        name.setText(persona.getname());
        time.setText(persona.getTime());
        Glide.with(context).load(persona.getimage()).into(image);

    }

}`



When I press in "image.setOnclick", works perfectly, when i press in view, doesn't work...

**Comment by rajsuvariya** [comment]
@mandybess Please have a look at it.

**Comment by traifdevelopment** [comment]
Tell me when you can. Im with this library in my job...
Thanks.
