### ISSUE TITLE
RecyclerView HEIGHT=WRAP_CONTENT not working (hasFixedSize=true, setNestedScrollingEnabled=false)

### ISSUE THREAD

**Issue by felipefpx** [thoughtbot/expandable-recycler-view#53]
I'm trying to implement an expandable list using this library but I need that my RecyclerView working with WRAP_CONTENT (auto update of height attribute).

I used hasFixedSize = true and setNestedScrollingEnabled=false but the LinearLayoutManager doesn't update the RecyclerView size.

My layout hierarchy will be like this:
= FrameLayout
== LinearLayout (Vertical)
=== LinearLayout (Horizontal)
=== RecyclerView
== LinearLayout (Vertical)

There are a custom layout manager to make this work? Thanks

**Comment by rajsuvariya** [comment]
What are you getting as a result?

**Comment by felipefpx** [comment]
My RecyclerView get the initial height according with my groups, but after expand the groups, the height is not updated.

**Comment by moeintav** [comment]
hi this is my layout 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingBottom="@dimen/_16cdp"
    android:paddingLeft="@dimen/_16cdp"
    android:paddingRight="@dimen/_16cdp"
    android:paddingTop="@dimen/_16cdp"
    tools:context="com.example.android2.myapplication.chitva_activities.MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/commentList"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />


    <android.support.design.widget.FloatingActionButton
        android:id="@+id/addItem"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_gravity="right|end"
        android:layout_marginTop="@dimen/_16cdp" />

</RelativeLayout>

 I have same problem and when I am expanded the list the height of list is not updated and the group for one second were hidden but when I read your issu I am understand that you should set your hieght of recyclerview to match_parent

**Comment by moeintav** [comment]
and the parent of them is a relative layout

**Comment by rajsuvariya** [comment]
@mandybess please look into this issue

**Comment by felipefpx** [comment]
@moeintav We need to set it to wrap_content, because the RecyclerView should increase its size based on the size of its children.

**Comment by faruqy87** [comment]
please.. somebody fix this, this is a critical issue

**Comment by margin555** [comment]
i suggest you to put the recyclerview in any other layout (Relative layout is preferable). Then change recyclerview's height/width as match parent to that layout and set the parent layout's height/width as wrap content. it works for me

**Comment by nicparmee** [comment]
@margin555 you are 100% right just needs to be in another layout but that layout MUST be relative view.

**Comment by Polovykh** [comment]
@margin555 , thanks

**Comment by aungtuntun** [comment]
@margin555 , thanks,
 I removed NestedScrollView and put RecyclerView into RelativeLayout. Now here is my layout:
<layout>
<CoordinatorLayout>
<AppBarLayout>
<ToolBar />
</AppBarLayout>
<RelativeLayout>
<RecyclerView />
</RelativeLayout>
<FloatingActionButton />
</CoordinatorLayout>
</layout>

**Comment by thanhlcm90** [comment]
@margin555 Amazing ! Many thanks.

**Comment by Sabbo0** [comment]
@margin555 Thanks for the solution. It works great.

**Comment by Digital4design** [comment]
Put the RecyclerView into NestedScrollView like this
`<android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>
</android.support.v4.widget.NestedScrollView>`

and remove the `android:nestedScrollingEnabled="false"` from RecyclerVeiw

**Comment by adityapp** [comment]
> @moeintav We need to set the height parameter of RecyclerView to wrap_content, because the RecyclerView should increase its size based on the size of its children.

thank you dude

**Comment by rcoelhoAtterbury** [comment]
Switching to RelativeLayout worked when adding items to Recycler that initially had some items. But it did not work, when Recycler started out empty. Adapter's ItemCount and OnBind was getting called correctly; but the screen area was not getting redrawn. What finally worked for me, was to override OnLayout and force the RecyclerView to View.Layout. [Note: invoking View.Layout on the RelativeLayout was insufficient, it did not trickle down to the Recycler].

**Comment by vishwapratap** [comment]
@margin555 you are 100% right just needs to be in another layout but that layout MUST be relative view. This works for me.

**Comment by Abhishekgarg727** [comment]
> Putting recycler view inside in the relative layout works well, to acheive same wrap content effect. 

**for example** i have screen in which multiple recycle views are present, in that i can not set recycle view height as match parent, but without match parent height recycle view seems only show my first element, in that case i **wrap my recycle view** inside a relative layout while **put relative layout height as wrap content** while putting **recycle view height as match parent**, below is sample example xml.

```
<androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fillViewport="true">

       <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                <androidx.recyclerview.widget.RecyclerView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"/>
        </RelativeLayout>

       <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                <androidx.recyclerview.widget.RecyclerView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"/>
        </RelativeLayout>

       <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                <androidx.recyclerview.widget.RecyclerView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"/>
         </RelativeLayout>

        <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                <androidx.recyclerview.widget.RecyclerView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"/>
        </RelativeLayout>

       <Button
                   android:text="Sample"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"/>

</NestedScrollView>
```

**Comment by yoanngoular** [comment]
> 
> 
> i suggest you to put the recyclerview in any other layout (Relative layout is preferable). Then change recyclerview's height/width as match parent to that layout and set the parent layout's height/width as wrap content. it works for me

Thanks a lot

**Comment by selfconzrr** [comment]
> i suggest you to put the recyclerview in any other layout (Relative layout is preferable). Then change recyclerview's height/width as match parent to that layout and set the parent layout's height/width as wrap content. it works for me

thanks a lot，it works for me. But why?

**Comment by burakkarabekir** [comment]
it works fine but any way to store list more efficient?

**Comment by Akramammar** [comment]
It didn't work with androidx's recycler view, any help please??

**Comment by developervineetjoshi** [comment]
Just delete 
Recyclerview.setHasFixedSize(true);
from your code if you are setting it to wrap the content

**Comment by venusaim23** [comment]
Hello there,
I'm having the same issue with recyclerView.
It seems that even on setting the height of of recyclerView as "wrap content", it achieves the max height as that of the layout.
I tried all the solutions above like putting the recyclerView in a different layout and setting the layout's height as wrap content.
I even tried adding a FrameLayout to the parent layout and embedding a new fragment inside it with recyclerView.
Nothing seems to work for me :(
Here's a screenshot how it looks:
![ss](https://user-images.githubusercontent.com/75775529/105742726-e138e200-5f61-11eb-8534-cdaae6111edd.jpeg)

Someone please help me out. I'm trying to find a solution to this for too long and couldn't find anywhere.

**Comment by prabhatsdp** [comment]
> Just delete Recyclerview.setHasFixedSize(true); from your code if you are setting it to wrap the content

Thanks a ton, it worked for me.

**Comment by venusaim23** [comment]
I figured out that RecyclerView has a flaw with ConstraintLayout. Even if you set the top and bottom constraints for the recyclerView and set its height to "wrap_content", it goes out of screen when the items are filled up and the max height it acquired is that of screen height. A quick fix for this is to migrate the layout to RelativeLayout, define layout_above and layout_below attributes. Height can either be "wrap_content" or "match_parent", the recyclerView will constrain itself within the limits.

**Comment by venusaim23** [comment]
> I figured out that RecyclerView has a flaw with ConstraintLayout. Even if you set the top and bottom constraints for the recyclerView and set its height to "wrap_content", it goes out of screen when the items are filled up and the max height it acquired is that of screen height. A quick fix for this is to migrate the layout to RelativeLayout, define layout_above and layout_below attributes. Height can either be "wrap_content" or "match_parent", the recyclerView will constrain itself within the limits.

If nothing from the above solutions work, this might still work. Try it

**Comment by yogithesymbian** [comment]
> set the p

doesnt work , my entier screen still have space when deleting item on recycler on bottom sheet

**Comment by oguzhanaslann** [comment]
just be a note here, Using constraint layout as parent did not worked for me but RelativeLayout did
