### ISSUE TITLE
Does it support subgroups and subchildren?

### ISSUE THREAD

**Issue by malhobayyeb** [thoughtbot/expandable-recycler-view#57]
My scenario is as follow:

I have categories and subcategories and there is not limit to the depth of subcategories. (sub sub sub sub ..etc)

I also have products for each categories, these products have sub products, too.

**Comment by rajsuvariya** [comment]
Why you want to add subgroups and sub children that will be 4 levels

**Comment by denisrai** [comment]
Hey @malhobayyeb did you find a solution?

Cheers,
