### ISSUE TITLE
Expand groups for the first time in onCreateGroupViewHolder()

### ISSUE THREAD

**Issue by HoLuong0211** [thoughtbot/expandable-recycler-view#60]
Is there any idea for expanding groups for the first time launching recyclerview, here is my code but it has problem when I click to collapse the second time, it go into animateExpand() so that my indication arrow not animate the right way:

`@Override
    public ChatGroupParentVH onCreateGroupViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(mContext)
                .inflate(R.layout.item_header, parent, false);
        final ChatGroupParentVH holder = new ChatGroupParentVH(itemView);
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                holder.expand();
                onGroupClick(holder.getAdapterPosition());
            }
        });
        return holder;
    }

Thank you!`

**Comment by mandybess** [comment]
I would recommend using one of the `adapter.toggleGroup()` methods to toggle a group. This will ensure the `expandCollapseController` is aware of the expanded / collapsed state of all groups. The adapter uses this class to determine whether to call `expand` or `collapse` animations. So if that controller becomes out of sync, that is one reason why you might be seeing the wrong animations being called.

**Comment by HoLuong0211** [comment]
@mandybess I replaced `onGroupClick(holder.getAdapterPosition());` method by `toggleGroup(holder.getAdapterPosition())` but it still the same, my indication arrow still not animate the right way.
Can you explain with a little more detail about your idea for this issue.

Thank you for your help!

**Comment by mandybess** [comment]
If you are calling this method inside `onCreateGroupViewHolder` then all of the work is being executed before the group click listener is applied to the group view holder. That might be why you are experiencing some weirdness. I would recommend calling `toggleGroup` after the adapter has had a chance to create and bind all view holders

**Comment by HoLuong0211** [comment]
@mandybess I moved all code from ChatGroupAdapter to my Activity:

`List<ParentExpandable> expandableList = getListChatGroup();
        final ChatGroupAdapter adapter = new ChatGroupAdapter(this, expandableList);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(adapter);
        if (adapter.getGroups().size() > 0) {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i < adapter.getGroups().size(); i++) {
                        ChatGroupParentVH holder = (ChatGroupParentVH) recyclerView.getChildViewHolder(recyclerView.getChildAt(i));
                        adapter.toggleGroup(holder.getAdapterPosition());
                        holder.expand();
                    }
                }
            }, 1000);
        }`

The group items was expanding for the first time and the indication arrow animate the right way, but when I click on the indication arrow for the second time it still when to `ChatGroupParentVH.expand()` method.
Or maybe I didn't get your idea. Could you please explain your solution for this issue.

Thank you so much!

**Comment by vfa-tuantt** [comment]
I have solution for you @HoLuong1609 
In function onBindGroupViewHolder of Adapter please check:
```
boolean isExpand = isGroupExpanded(flatPosition);
if(group instanceof ChatGroupParentVH){
         if(isExpand){
               ((ChatGroupParentVH) holder).animateExpand(0);
         }else {
               ((ChatGroupParentVH) holder).animateCollapse(0);
         }
 }

```
You can preference the code of animateExapand below
```
public ObjectAnimator createRotateAnimator(final View target, final float from, final float to, int duration) {

        ObjectAnimator animator = ObjectAnimator.ofFloat(target, "rotation", from, to);
        animator.setDuration(duration);
        animator.setInterpolator(Utils.createInterpolator(Utils.LINEAR_INTERPOLATOR));
        return animator;
    }
    private void animateExpand(int duration) {
        createRotateAnimator(view, 0f, 180f,duration).start();
    }

    private void animateCollapse(int duration) {
        createRotateAnimator(view, 180f, 0f,duration).start();
    }

```
