### ISSUE TITLE
App crashes with empty list

### ISSUE THREAD

**Issue by Almaral-Engineering** [thoughtbot/expandable-recycler-view#61]
When you start an adapter with an empty list like:

```
ArrayList<GroupObject> groupObjectList = new ArrayList<GroupObject>
MyAdaper adapter = new MyAdapter(groupObjectList)
```

it crashes, so for example if you are downloading objects and get an empty list you have to do some workarounds to use the adapter. I think this is because the `numberOfVisibleItemsInGroup` in `ExpandableListClass` always returns 1 or more, so it´s getting a `java.lang.ArrayIndexOutOfBoundsException: length=0; index=0`

**Comment by chewenkai** [comment]
Hello, I encounter the same problem, it is exactly same as yours. Can you show your solution here? Really thanks

**Comment by xPryds** [comment]
Same problem here, don't know how to fix.

**Comment by ugurcany** [comment]
+1

**Comment by jeancsanchez** [comment]
@Almaral-Engineering  Some solution for this issue?

**Comment by ash2osh** [comment]
+1

**Comment by sudarshan103** [comment]
Create copies of ExpandableList & ExpandableRecyclerViewAdapter in your project.
Modify ExpandableList function : 

 private int numberOfVisibleItemsInGroup2(int group) {
        if(expandedGroupIndexes!=null && expandedGroupIndexes.length>0) {
            if (expandedGroupIndexes[group]) {
                return groups.get(group).getItemCount() + 1;
            } else {
                return 1;
            }
        }
        return 0;
    }

Use the modified list in your copied  ExpandableRecyclerViewAdapter.
Use the pair of these 2 modified classes.

**Comment by Condastry** [comment]
https://github.com/thoughtbot/expandable-recycler-view/issues/61#issuecomment-493419380

As i understood, the solution provided above is incorrect. **Dont use it**. Follow the solution, provided by link below instead, without any modifying of library source code:

**https://github.com/thoughtbot/expandable-recycler-view/issues/27#issuecomment-448226409**

**Comment by sudarshan103** [comment]
> [#61 (comment)](https://github.com/thoughtbot/expandable-recycler-view/issues/61#issuecomment-493419380)
> 
> As i understood, the solution provided above is incorrect. **Dont use it**. Follow the solution, provided by link below instead, without any modifying of library source code:
> 
> **[#27 (comment)](https://github.com/thoughtbot/expandable-recycler-view/issues/27#issuecomment-448226409)**

The mentioned solution is worked for me, even the edited version of comment is a working solution. Done some edits to make it more clear.
