### ISSUE TITLE
Is it possible to implement filterable?

### ISSUE THREAD

**Issue by hackaprende** [thoughtbot/expandable-recycler-view#62]
Hi, I am filtering some objects using a searchview, is it posible to do it with this library? What would be a possible implementation

**Comment by ericmguimaraes** [comment]
+1

**Comment by iittuski** [comment]
hie. i have the same issue....were you able to fix that??

**Comment by SachinKasaraddi** [comment]
+1

**Comment by alishawky212** [comment]
Is there any one solve it ?
