### ISSUE TITLE
Closed group programmatically, won't open again. 

### ISSUE THREAD

**Issue by kukamanga** [thoughtbot/expandable-recycler-view#64]
I use these lines of code when group is expanded and close others, and after a group is collapsed and try to open the same again, it won't open, but when I try to open another group works fine.

 @Override public void onGroupExpanded(ExpandableGroup group) {
        if (mLastExpandedGroup != null) {
          adapter.toggleGroup(mLastExpandedGroup);
        }
        mLastExpandedGroup = group;
      }

**Comment by kukamanga** [comment]
# #25 #issuecomment-329484599

**Comment by washul** [comment]
Did you find a solution?
@kukamanga 

my problem, It works fine when the previously expanded group is visible on the screen. If the group is off the screen, it will not collapse when calling toggleGroup on it.
