### ISSUE TITLE
CheckableChildRecyclerViewAdapter check mark of CheckedTextView gets reset

### ISSUE THREAD

**Issue by yavski** [thoughtbot/expandable-recycler-view#67]
1. Say view item at index 20 is a group that's been expanded
2. Scroll up only as little as it's needed for the view at index 19 to go off the screen
3. Scroll down to the expanded group view such that it's fully visible
4. Observe the state of the check mark 

Actual result: The check mark has been reset to its collapsed state
Expected result: The check mark remains in expanded state

**Comment by giusha** [comment]
I have the same problem, my check marks are changing position, for example when I check position 19 after scroll it may be changed to 20,21,18,17 or unchecked at all. Is there any fix yet?

**Comment by saurabhdhillon** [comment]
@yavski @giusha In the parent holder where you are setting text to the parent view maintain a boolean variable for the checkstate of that item. Everytime you scroll down or up, the view is recreated and in case you have not handled the check/uncheck depending on your selection it will revert it to default values of the view
Here is the piece of code i have an arrow which changes orientation on expand and collapse, so i save the state in a boolean variable everytime i expand/collapse, and when the view is reinitialied i use the same boolean value for setting it to desired state(expand/collapse)

```
public void setFloorText(ExpandableGroup group) {
        tvFloor.setText(group.getTitle());
        if (isExpanded) {
            expandAnimation();
        }
        if (isCollapsed) {
            collapseAnimation();
        }
    }

private void collapseAnimation() {
        isExpanded = false;
        isCollapsed = true;
        collapseAnim = AnimationUtils.loadAnimation(context, R.anim.roatate_collapse);
        collapseAnim.setFillAfter(true);
        ivArrow.startAnimation(collapseAnim);
    }

    private void expandAnimation() {
        isExpanded = true;
        isCollapsed = false;
        expandAnim = AnimationUtils.loadAnimation(context, R.anim.roatate_expand);
        expandAnim.setFillAfter(true);
        ivArrow.startAnimation(expandAnim);
    }
```

**Comment by yavski** [comment]
@saurabhdhillon yeah, I'm already doing that, the problem is that `CheckableChildRecyclerViewAdapter` does not invoke the callback `onBindGroupViewHolder(...)` for me to update the state of the view. Have a look at the attached video (pay attention to the arrow to the right of CFD Forward 53).


[device-2017-08-10-114918.zip](https://github.com/thoughtbot/expandable-recycler-view/files/1214238/device-2017-08-10-114918.zip)

**Comment by jinujayakumar** [comment]
Hi @yavski  i'm facing the same issue did you find any solution?

**Comment by yavski** [comment]
@jinujayakumar, nope I couldn't resolve it.

**Comment by mars885** [comment]
Any progress on this problem? Anyone? Same issue here. Would be interesting to find out what the cause is.

**Comment by mars885** [comment]
Well, it looks like I found the problem. The thing was that the view animations were used (RotateAnimation, in my case) to rotate the icon or whatever view you are animating. This type of animation changes only where the view is drawn, but not the actual view itself. So, you first run these animations, the view is artificially animated, you scroll off and back, onDraw is called and draws the view based on its properties (which remember were not changed), and, as a result, the view appears to reset its state. So to solve it, you basically need to replace [view animations](https://developer.android.com/guide/topics/graphics/view-animation.html) with [property animations](https://developer.android.com/guide/topics/graphics/prop-animation.html).

**Comment by tjwpdl** [comment]
Thanks, I had to change many things but I got it working with @saurabhdhillon's post + @mars885's post, and this is how I did the property animations: 

    private void animateExpand2(model_category category){ // property animation
        category.expanded = true;
        ObjectAnimator animation = ObjectAnimator.ofFloat(ivCategoryArrow, "rotation", 180f);
        animation.setDuration(0);
        animation.start();
    }

    private void animateCollapse2(model_category category){ // property animation
        category.expanded = false;
        ObjectAnimator animation = ObjectAnimator.ofFloat(ivCategoryArrow, "rotation", 0f);
        animation.setDuration(0);
        animation.start();
    }

**Comment by paveltech** [comment]
@tjwpdl  can you share your code i am also facing this issue.

**Comment by liguopengbenli** [comment]
I try all that and it still has some issues. finally I notice I it's a recycleview in scroll view. I Have to set             android:nestedScrollingEnabled="false" and parent scroll view to nested scroll view, 
It works well. I don't use the properties animation or anthing else. The expand and collapse callback works now. 

```
  override fun expand() {
        super.expand()
        toggleArrow(arrow, true)
    }

    override fun collapse() {
        super.collapse()
        toggleArrow(arrow, false)
    }
```
