### ISSUE TITLE
Remove Child from list and everything updates?

### ISSUE THREAD

**Issue by Chaseos** [thoughtbot/expandable-recycler-view#73]
I'm having trouble figuring out how to remove a child and have the whole list update including if there are 0 children remaining in the parent, it removes itself as well. The only solution I've found is reloading the whole UI and list again, instead of it updating smoothly.

**Comment by VanDucit7** [comment]
In class ExpandableRecyclerViewAdapter you add method:

public void removeItem(int position) {
        ExpandableListPosition listPos = expandableList.getUnflattenedPosition(position);
        ExpandableGroup group = expandableList.getExpandableGroup(listPos);
        switch (listPos.type) {
            case ExpandableListPosition.CHILD:
                group.remove(listPos.childPos);
                if (group.getItemCount() == 0) {
                    expandableList.remove(listPos.groupPos);
                    notifyItemRangeRemoved(position - 1, 2);
                } else {
                    notifyItemRemoved(position);
                }
                break;
        }
    }

In Class ExpandableGroup you add method:

 public void remove(int position) {
        items.remove(position);
    }

In Class ExpandableList you add method:

 public void remove(int groupIndex) {
        this.groups.remove(groupIndex);
        boolean[] expandedGroupIndexesTemp = expandedGroupIndexes.clone();
        expandedGroupIndexes = new boolean[groups.size()];
        for (int i = 0; i < groups.size(); i++) {
            if (i < groupIndex) {
                expandedGroupIndexes[i] = expandedGroupIndexesTemp[i];
            } else {
                expandedGroupIndexes[i] = expandedGroupIndexesTemp[i + 1];
            }
        }
    }

Current I only remove child.

**Comment by dwsmagar** [comment]
Would you please clearify it?
