### ISSUE TITLE
Exapend/collapse group bug

### ISSUE THREAD

**Issue by ValBrunhes** [thoughtbot/expandable-recycler-view#82]
When I extend the first group and then I collapse it the second group is duplicated like in the picture.
Has anyone ever had this bug? And could help me?
Thanks 
![screenshot_2017-07-04-11-49-19 1](https://user-images.githubusercontent.com/9082048/27825316-6d690bf2-60af-11e7-8d5b-d48a14d1fabc.png)

**Comment by rajsuvariya** [comment]
I am using the same library and not able to reproduce your bug. Please check your code, you might be doing something wrong

**Comment by ValBrunhes** [comment]
It's ok. I found the problem but forgot to close the issue.

**Comment by Corical** [comment]
Nice that you shared your resolution, thank you for the contribution.

**Comment by KairaTawer** [comment]
@ValBrunhes Can you provide the way how you fixed this problem and what was the problem?
