### ISSUE TITLE
OnChildClickListener with ExpandableRecyclerView

### ISSUE THREAD

**Issue by traifdevelopment** [thoughtbot/expandable-recycler-view#83]
How I can do a child click listener?

Thanks.

**Comment by cristianego** [comment]
public class ArtistViewHolder extends ChildViewHolder {

  private TextView artistName;

  public ArtistViewHolder(View itemView) {
    super(itemView);
    artistName = itemView.findViewById(R.id.artist_name);
//add listener here
artistName.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
            
            }
        });
  }

  public void onBind(Artist artist) {
    artistName.setText(artist.getTitle());
  }
}

**Comment by prabhat1707** [comment]
how to pass position of chilld??

**Comment by samybeng** [comment]
Why you need the child position for ?

**Comment by traifdevelopment** [comment]
Because i need call a intent with a id.

**Comment by samybeng** [comment]
Can what  explain more what you want to do ? Especially what you want to achieve ?

**Comment by traifdevelopment** [comment]
For example, i have a person list.

Person have name, picture, description.

Group list -> Classroom
Child list-> Persons

Click on childlist --> person id --> activity description (show name,
picture, description).

2017-07-18 15:45 GMT+02:00 samybeng <notifications@github.com>:

**Comment by cristianego** [comment]
you can implement Persons item click listener, and get person.getId(). or Artis
you need add a Interface onItemClickListener on GenreAdapter
then


 `GenreAdapter adapter = new GenreAdapter(genres);`
change to
` GenreAdapter adapter = new GenreAdapter(genresnew, GenreAdapter.OnItemClickListener() {
                        @Override
                        public void onItemClick(Artis items) {
                          //here you get Artis or person items
                        }
                    });`


and need add on GenreAdapter ...
`private final GenreAdapter.OnItemClickListener listener;`
add listener to constructor
`
public GenreAdapter(List<? extends ExpandableGroup> groups, OnItemClickListener listener) {
        super(groups);
        this.listener=listener;
    }
`
add interface...
`  public interface OnItemClickListener {
        void onItemClick(Artis items);
    }`
and add binData method on onBindChildViewHolder
` holder.binDatos(artist,listener);`


and finally change ArtistViewHolder

`public void binData(final Artis items, final GenreAdapter.OnItemClickListener listener) {
        childTextView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
            listener.onItemClick(items);
            }
        });
    }`

**Comment by traifdevelopment** [comment]
But childTextView only respond in textview, i need respond in view.

**Comment by cristianego** [comment]
set on click listener over itemView

**Comment by prabhat1707** [comment]
but I think again it work as click listener on text view but I need to also pass position and then acc to it open new activity I try many possible ways but it not works....

**Comment by cristianego** [comment]
set onclick listener over itemView, work for all item view.

`itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                listener.onItemClick(items);
            }
        });`

you have item at this position, and you can get Artis.getId, Artis.getName, whatever you need from Artis class

**Comment by traifdevelopment** [comment]
I don't understand why doesn't work for me.

**My code:**

`public class CViewHolder extends ChildViewHolder implements View.OnClickListener{


    private OnItemClickListener listener;

    public CViewHolder(final View itemLayoutView, final Context context,final OnItemClickListener listener) {
        super(itemLayoutView);

        this.listener = listener;
        itemView.setOnClickListener(this);

    }

    public void onBind(final RecetaChildBean recetaChildBean, final String horarioComida) {
        /*CODE WORK*/

    }

    @Override
    public void onClick(View view) {
        if(listener != null){
            listener.onItemClick(getLayoutPosition());
        }
    }

    public interface OnItemClickListener {
        void onItemClick(int position);
    }
}`





`public class ExpandableAdapter extends ExpandableRecyclerViewAdapter<PViewHolder, CViewHolder> {
	Context c;
    CViewHolder.OnItemClickListener listener;
    public ExpandableAdapter(List<? extends ExpandableGroup> groups, Context c, CViewHolder.OnItemClickListener listener) {
        super(groups);
        this.c = c;
        mInflater = LayoutInflater.from(c);

        this.listener = listener;
    }
    @Override
    public PViewHolder onCreateGroupViewHolder(ViewGroup parent, int viewType) {
        View view = mInflater.inflate(R.layout.p, parent, false);
        return new PViewHolder(view);
    }
    @Override
    public CViewHolder onCreateChildViewHolder(ViewGroup parent, int viewType) {

        return new CViewHolder(view, c, listener);
    }
    @Override
    public void onBindChildViewHolder(CViewHolder holder, int flatPosition, ExpandableGroup group, int childIndex) {
        final Person p = ((Person) group.getItems().get(childIndex));

        holder.onBind(p, group.getTitle());

    }
    @Override
    public void onBindGroupViewHolder(PViewHolder holder, int flatPosition, ExpandableGroup group) {
        holder.setGenreTitle(group);
    }
}`


`  ExpandableAdapter adapter = new ExpandableAdapter(group, getContext(), new CViewHolder.OnItemClickListener() {
                    @Override
                    public void onItemClick(int position) {
                       //SOMETHING
                    }
                });`


What is wrong?

**Comment by cristianego** [comment]
ok, let me try implement with your variable names

`public class CViewHolder extends ChildViewHolder {

    public CViewHolder(final View itemView) {
        super(itemView);

    }

    public void onBind(final RecetaChildBean recetaChildBean, final String horarioComida,ExpandableAdapter.OnItemClickListener listener) {
    /*CODE WORK*/
        itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                listener.onItemClick(recetaChildBean);
            }
        });
    }
}
`
in ExpandableAdapter you need implement
`public class ExpandableAdapter extends ExpandableRecyclerViewAdapter<PViewHolder, CViewHolder> {
Context c;
//ExpandableAdapter not CViewHolder
ExpandableAdapter.OnItemClickListener listener;
public ExpandableAdapter(List<? extends ExpandableGroup> groups, Context c, OnItemClickListener listener) {
super(groups);
this.c = c;
mInflater = LayoutInflater.from(c);

    this.listener = listener;
}
@Override
public PViewHolder onCreateGroupViewHolder(ViewGroup parent, int viewType) {
    View view = mInflater.inflate(R.layout.p, parent, false);
    return new PViewHolder(view);
}
@Override
public CViewHolder onCreateChildViewHolder(ViewGroup parent, int viewType) {

    return new CViewHolder(view, c, listener);
}
@Override
public void onBindChildViewHolder(CViewHolder holder, int flatPosition, ExpandableGroup group, int childIndex) {
    final Person p = ((Person) group.getItems().get(childIndex));
//pass listener to ChildViewHolder
    holder.onBind(p, group.getTitle(),listener);

}
@Override
public void onBindGroupViewHolder(PViewHolder holder, int flatPosition, ExpandableGroup group) {
    holder.setGenreTitle(group);
}

 public interface OnItemClickListener {
        void onItemClick(RecetaChildBean items);
    }
}`


ExpandableAdapter adapter = new ExpandableAdapter(group, getContext(), new ExpandableAdapter.OnItemClickListener() { @Override public void onItemClick(RecetaChildBean items) { //SOMETHING } });

**Comment by traifdevelopment** [comment]
Doesn't work for me...

**Comment by oscarin13** [comment]
How can return the item select to my fragment/activity ?

**Comment by oscarin13** [comment]
How can change color of item child  selected

**Comment by lengsovandara** [comment]
Anyone solved this problem yet? if so, Please give me a solution.

**Comment by shawn-maybush** [comment]
I just called setTag on the holder.View in the OnBindChildViewHolder and passed the childindex to it. There you just implement View.OnClickListener from the ChildViewHolder and override onClick.

You create a clickHandler interface and have the activity implement it passing the childindex through.

**Comment by khoshrang** [comment]
just go to onBindChildViewHolder and add this  :1st_place_medal:        
`holder.itemView.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {
        Toast.makeText(mactive,artist.getName(),Toast.LENGTH_SHORT).show();

      }
    });`
if you can do this i guess you can do what you've in your mind too.

**Comment by shawn-maybush** [comment]
Well I extended the viewHolder as a View.OnclickListener and then holder.itemView.setOnclickListener(this).

Its a tad hacky using setTag but gets the job done. Though adding it to the object Im using and passing the index there as @smoothdvd suggested might be less hacky.
