### ISSUE TITLE
How can I do to open the children list by default？

### ISSUE THREAD

**Issue by EricSocrates** [thoughtbot/expandable-recycler-view#84]
I use the most easy expandable recyclerview.And I'd like to open the children list when they load first.

**Comment by rajsuvariya** [comment]
Go through this https://github.com/thoughtbot/expandable-recycler-view/issues/54#issuecomment-284171806

**Comment by EricSocrates** [comment]
Thanks you a lot.And it works for me.

**Comment by JainamJhaveri** [comment]
How to collapse all the children at one go?
