### ISSUE TITLE
Collapse All parents when another one is clicked

### ISSUE THREAD

**Issue by ziselos** [thoughtbot/expandable-recycler-view#85]
Is it possible to collapse the expanded parent when another one is clicked? So as only one parent to be expanded each time.

**Comment by abdyer** [comment]
@ziselos I accomplished that by overriding `onGroupExpanded` in my adapter:

```kotlin
    override fun onGroupExpanded(expandedGroup: ExpandableGroup<*>) {
        groups.filterNot { group -> group == expandedGroup }
                .filter { group -> isGroupExpanded(group) }
                .forEach { group -> toggleGroup(group) }
    }
```

**Comment by ziselos** [comment]
@abdyer Thank you for your respnose. If i got it right your code is in Kotlin, but i am not familiar with. Can you help me write it using java? I tried to collapse all parents except the one iwas  clicked but it did not work.
Thanks in advance.

**Comment by ashfaq22iit** [comment]
how can i get this expandedGroup?

**Comment by Lihacovs** [comment]
You can try to override onGroupExpanded method in your adapter, something like this:

`@Override`
`public void onGroupExpanded(int positionStart, int itemCount) {`
      `int groupIndex = expandableList.getUnflattenedPosition(positionStart).groupPos;`
           ` if (itemCount > 0) {`
                `notifyItemRangeInserted(positionStart, itemCount);`
                `for (ExpandableGroup grp : mGroups) {`
                    `if (grp != mGroups.get(groupIndex)) {`
                        `if (this.isGroupExpanded(grp)) {`
                            `this.toggleGroup(grp);`
                        `}`
                   ` }`
               ` }`
           ` }`
        `}`

code is not tested, probably it can produce errors on some cases. If you can develop working solution, please post results here

**Comment by ziselos** [comment]
Thanks for the response @Lihacovs ! I'll try it and if i find a working solution i will post the code.

**Comment by subairariyil** [comment]
Add this line if the above snippest didnt work.
adapter.notifyParentItemChanged(lastExpandedPosition);

**Comment by Lihacovs** [comment]
I had some time recently to test on this. Check my updated comment above.

**Comment by abunayem** [comment]
work. but animation has gone. on collapsing group item.

**Comment by Sibasish1992** [comment]
@Lihacovs  your solution work well.Just if we have any animation on View Holder then is will not execute.So we can fix it partially by overriding the **onBindViewHolder** method. But the thing is that with every expand all the collapsed viewholder execute the animation.

`    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        ExpandableListPosition listPos = expandableList.getUnflattenedPosition(position);
        ExpandableGroup group = expandableList.getExpandableGroup(listPos);
        switch (listPos.type) {
            case ExpandableListPosition.GROUP:
                onBindGroupViewHolder((PlaylistGroupVH) holder, position, group);

                if (isGroupExpanded(group)) {
                    ((PlaylistGroupVH) holder).expand();
                } else {
                    ((PlaylistGroupVH) holder).collapse();
                }
                break;
            case ExpandableListPosition.CHILD:
                onBindChildViewHolder((PlaylistVH) holder, position, group, listPos.childPos);
                break;
        }
    }`

**Comment by MangaOtaku** [comment]
Incase anyone else still trying to solve this, this works well and is pretty simple.

    lateinit var mAdapter : ExpandableRecyclerViewAdapter<ProductRecyclerViewAdapter.ParentViewHolder, ProductRecyclerViewAdapter.MyChildViewHolder>
    override fun onCreateGroupViewHolder(parent: ViewGroup, viewType: Int): ParentViewHolder {
        val view = LayoutInflater.from(parent.context)
                .inflate(R.layout.fragment_product_parent, parent, false)
        mAdapter = this
        mAdapter.setOnGroupExpandCollapseListener(object : GroupExpandCollapseListener {
            override fun onGroupCollapsed(group: ExpandableGroup<*>?) {
            }

            override fun onGroupExpanded(group: ExpandableGroup<*>) {
                mAdapter.groups.forEach { item ->
                    if(mAdapter.isGroupExpanded(item) && item != group) {
                        mAdapter.toggleGroup(item)
                    }
                }
            }
        })
        return ParentViewHolder(view)
    }

**Comment by fizzappy2016** [comment]
@Lihacovs Hey your response is working but 
 this.toggleGroup(grp); requires int

**Comment by fizzappy2016** [comment]
@Lihacovs Your code is working great but the animations are gone. @Sibasish1992  did you get solution for the animation?

**Comment by washul** [comment]
@Lihacovs it worked, now It works fine when the previously expanded group is visible on the screen. If the group is off the screen, it will not collapse when calling toggleGroup on it. Unless I am doing something wrong?,  @ziselos did you find a solution? or @Sibasish1992 can you helpme whit my problem?

**Comment by truXton222** [comment]
I solved by calling this method before clicking on group.

`    private void collapseAll() {
        for (int i=0;i<myAdapter.getGroups().size();i++) {
            if (myAdapter.isGroupExpanded(myAdapter.getGroups().get(i))) {
                myAdapter.toggleGroup(myAdapter.getGroups().get(i));
            }
        }
    }
`

**Comment by joseluisng** [comment]
@truXton222 Do you call the method before  public void onGroupExpanded(int positionStart, int itemCount)?

or where is clicking on group?

**Comment by RealDavid** [comment]
> @truXton222 Do you call the method before public void onGroupExpanded(int positionStart, int itemCount)?
> 
> or where is clicking on group?
You call it here, this method keeps the animation.
adapter.setOnGroupClickListener(new OnGroupClickListener() {
            @Override
            public boolean onGroupClick(int flatPos) {
                collapseAll();
                return false;
            }
        });

private void collapseAll() {
    for (int i=0;i<myAdapter.getGroups().size();i++) {
        if (myAdapter.isGroupExpanded(myAdapter.getGroups().get(i))) {
            myAdapter.toggleGroup(myAdapter.getGroups().get(i));
        }
    }
}
