### ISSUE TITLE
Bug when trying to toggle all groups.

### ISSUE THREAD

**Issue by benjosantony** [thoughtbot/expandable-recycler-view#87]
In the sample `ExpandActivity` I added the flowing line.

```java List<? extends ExpandableGroup> groups = adapter.getGroups();
    for (ExpandableGroup g : groups) {
      adapter.toggleGroup(g);
    }
```
**What I was thinking would happen**
All the groups would expand.
**What happened**
Only the `Rock` group was expanded.

**Comment by qbalsdon** [comment]
I can confirm this issue, and I only had 2 groups. However I "fixed" it by toggling the groups in reverse (the last group expanded first)

**Comment by rajsuvariya** [comment]
Actually, toggle group accepts flat position of the group view. So if there are expanded groups above then the flat position of that group you are trying to toggle will be different. For more info about flat position read this https://robots.thoughtbot.com/introducing-expandablerecyclerview

By doing it in reverse the group expanded below won't affect the flat position of the group you are trying to expand. So you can use it as trick
