### ISSUE TITLE
Bug in TOGGLE CLASSIC GROUP

### ISSUE THREAD

**Issue by benjosantony** [thoughtbot/expandable-recycler-view#88]
Toggling Classic Group using the button (`TOGGLE CLASSIC GROUP`)  only works if the groups above `classic` are collapsed. 

**Scenario** 
Rock group is expanded
**Action**
Click on  `TOGGLE CLASSIC GROUP` button. 
**Expectation**
Classic group is expanded.
**Result**
Classic groups is **not expanded**, and there is a weird animation (Slide in from bottom)on the group below classic (`salsa`).

**Comment by rajsuvariya** [comment]
toggle group accepts flat position so if the group above are expanded then you need to compute the flat position before adding it to toggle group.
for flat position read this https://robots.thoughtbot.com/introducing-expandablerecyclerview
