### ISSUE TITLE
minSdkVersion 能够调低一点吗？

### ISSUE THREAD

**Issue by iielse** [thoughtbot/expandable-recycler-view#89]
Error:Execution failed for task ':app:processDebugManifest'. > Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.thoughtbot:expandablerecyclerview:1.3] C:\Users\admin\.android\build-cache\ecc77b1faa9058c67e052b4923cda2f285e43795\output\AndroidManifest.xml 	Suggestion: use tools:overrideLibrary="com.thoughtbot.expandablerecyclerview" to force usage

**Comment by rajsuvariya** [comment]
You can change your minSdkVersion in your app/build.gradle file. By using version 16 your app will be compatible for 95% + users.
