### ISSUE TITLE
Is it possible to Single/MultiCheck parent only?

### ISSUE THREAD

**Issue by omrkhld** [thoughtbot/expandable-recycler-view#9]
Currently it seems that I could put the checkboxes or radio buttons on the children, but I'm looking for a way to put the radio button on the parents only. Is this possible?

**Comment by mandybess** [comment]
Hiya @omrkhld! You can add whatever widgets or views to the parent that you'd like view your extension of `GroupViewHolder` - i.e. any widget that extends `Checkable`. If you want to track what groups are "checked" you would have to do that yourself via the `GroupExpandCollapseListener`
