### ISSUE TITLE
How to Search the list (groups) 

### ISSUE THREAD

**Issue by iittuski** [thoughtbot/expandable-recycler-view#92]
Hi all, 
I want to search the list(groups) according to the given specified editext and filter the results accordingly to the given name searched and accordingly filter the list according to that.
plz help.

**Comment by srikanthnama** [comment]
Did you get solution for this? I am also facing same issue.. Please help

**Comment by Suganyasrii** [comment]
Use this method ,i got a solution..
 private ArrayList<CategoryItem> storeList_datas=new ArrayList<>();
CategoryItem is a model class which contain product list and category name,id
//Search view method
    private void SearchStringQueryMethod(String query) {
    final List<CategoryItem> filteredModelList = searchFilter(storeList_datas, query);
        if (productSearchItemAdapter != null) {
            array_list_count = filteredModelList.size();
            Log.e("array_list_count", "" + array_list_count);

            productSearchItemAdapter.setParentList((ArrayList<CategoryItem>) filteredModelList, false);
            productSearchItemAdapter.notifyDataSetChanged();
            productSearchItemAdapter.notifyParentDataSetChanged(false);
            productSearchItemAdapter.SetFilterSearchArrayItems((ArrayList<CategoryItem>) filteredModelList);
            productSearchItemAdapter.notifyDataSetChanged();
          

        }
    }

    private List<CategoryItem> searchFilter(List<CategoryItem> models, String query) {
        query = query.toLowerCase();


        final List<CategoryItem> filteredModelList = new ArrayList<>();

        Log.e("query",query);
        Log.e("models",""+models.size());
        for (CategoryItem model : models) {

                List<ProductList_Data> productList_datas = model.getSubfilterLists();
                ArrayList<ProductList_Data> newList = new ArrayList<ProductList_Data>();
                for(ProductList_Data productList_data: productList_datas){
                    if(productList_data.getproductName().toLowerCase().contains(query)){
                        newList.add(productList_data);
                    }
                }
                Log.e("new list_size",""+newList.size());
                if(newList.size() > 0){
                    Log.e("if new lsit",":if new list con");

                    Log.e("categoryItem",model.getCategoryname());

                    CategoryItem categoryItem = new CategoryItem(model.getCategoryname(),model.getCategroy_id(),model.getCategory_image(),newList);
                    filteredModelList.add(categoryItem);
                    Log.e("filter_model_list","------"+filteredModelList.size());


                }

//                else{
//
//                    home_search_empty_txt_view.setVisibility(View.VISIBLE);
//                    Log.e("emptylist","No data found");
//                }
            }


        return filteredModelList;
    }

    @Override
    public boolean onQueryTextSubmit(String query) {
        Log.e("onQueryTextSubmit","onQueryTextSubmit");
//        final List<CategoryItem> filteredModelList = searchFilter(storeList_datas, query);
//        if (productSearchItemAdapter != null && productSearchItemAdapter.getItemCount() != 0) {
//            array_list_count = filteredModelList.size();
//
//            productSearchItemAdapter.setParentList((ArrayList<CategoryItem>) filteredModelList, false);
//            productSearchItemAdapter.notifyDataSetChanged();
//            productSearchItemAdapter.expandAllParents();
////            productSearchItemAdapter.notifyParentDataSetChanged(true);
////            productSearchItemAdapter.filterData(query);
//

//
//        }

        return false;


    }

    @Override
    public boolean onQueryTextChange(String newText) {
        Log.e("onQueryTextChange","onQueryTextChange");
        Log.e("newText",""+newText);


            Log.e("else","-----");
            FilterMethod(newText);




        return true;
    }

    private void FilterMethod(String newText) {
        Log.e("store_list_data",""+storeList_datas.size());
        final List<CategoryItem> filteredModelList = searchFilter(storeList_datas, newText);
        Log.e("outside_the_adapter","----"+productSearchItemAdapter.getItemCount());

        if (productSearchItemAdapter != null) {

            Log.e("inside_the_adapter","----"+productSearchItemAdapter.getItemCount());
            array_list_count = filteredModelList.size();

            productSearchItemAdapter.setParentList(filteredModelList, false);
//            productSearchItemAdapter.notifyDataSetChanged();

            productSearchItemAdapter.notifyParentDataSetChanged(true);
            productSearchItemAdapter.expandAllParents();
//            productSearchItemAdapter.filterData(query);

            Log.e("filtermodel_size","----"+filteredModelList.size());

      

        }


    }

**Comment by Suganyasrii** [comment]
In Adapter class use this method
    public void SetFilterSearchArrayItems(ArrayList<CategoryItem> storeList_datas) {
        this.parentList = storeList_datas;
        Log.e("method_changed","Method Called");
        notifyParentDataSetChanged(true);
    }

**Comment by srikanthnama** [comment]
@Suganyasrii , Thanks for the solution.. I couldnt find notifyParentDataSetChanged(true) method in this solution.. What needs to be done there?

**Comment by Suganyasrii** [comment]
Otherwise use notifyDatasetChanged

**Comment by Suganyasrii** [comment]
I used the below gradle for the expandable recyclerview search functionality "compile 'come. bigne rdranch.android:expandablerecyclerview:3.0.0-RC1' , in that notifyParentDataSetChanged is available

**Comment by srikanthnama** [comment]
can you send me decoupled sample.. I am confused with the methods being used in the adapter, where to send the filtered list & parent list

**Comment by Suganyasrii** [comment]
public class ProductSearchItemAdapter  extends ExpandableRecyclerAdapter<CategoryItem, ProductList_Data, ProductSearchItemAdapter.CateViewHolder, ProductSearchItemAdapter.ProductCateViewHolder> {

    private LayoutInflater mInflater;

    
    ArrayList<CategoryItem> parentList;
   
    Context context;

    private ArrayList<CategoryItem> originalList;
    public ProductSearchItemAdapter(Context context, ArrayList<CategoryItem> parentList) {
        super(parentList);
        mInflater = LayoutInflater.from(context);
        this.parentList=parentList;
        this.context=context;
     
        this.originalList = new ArrayList<CategoryItem>();
        this.originalList.addAll(parentList);
        Log.e("parent_list",""+parentList.size());
    }


    @NonNull
    @Override
    public ProductSearchItemAdapter.CateViewHolder onCreateParentViewHolder(@NonNull ViewGroup parentViewGroup, int viewType) {
        View categoryview = mInflater.inflate(R.layout.modified_product_category_item, parentViewGroup, false);
        return new CateViewHolder(categoryview);
    }

    @NonNull
    @Override
    public ProductSearchItemAdapter.ProductCateViewHolder onCreateChildViewHolder(@NonNull ViewGroup childViewGroup, int viewType) {
        View subcateview = mInflater.inflate(R.layout.restaurant_menu_list_item, childViewGroup, false);
        ProductCateViewHolder holder = new ProductCateViewHolder(subcateview);
        return holder;

    }

    @Override
    public void onBindParentViewHolder(@NonNull ProductSearchItemAdapter.CateViewHolder parentViewHolder, int parentPosition, @NonNull CategoryItem parent) {
        parentViewHolder.bind(parent);

    }



    @Override
    public void onBindChildViewHolder(@NonNull ProductSearchItemAdapter.ProductCateViewHolder childViewHolder, int parentPosition, int childPosition, @NonNull ProductList_Data child) {
        childViewHolder.bind(child, childPosition);
    }


    public void SetFilterSearchArrayItems(ArrayList<CategoryItem> storeList_datas) {
        this.parentList = storeList_datas;
        Log.e("method_changed","Method Called");
//        notifyDataSetChanged();
        notifyParentDataSetChanged(true);
    }





    public class CateViewHolder extends ParentViewHolder {

        public TextView menu_category_item_text;
        public LinearLayout linearLayout;
        public ImageView arrow_iamge;

        public CateViewHolder(View itemView) {
            super(itemView);

            menu_category_item_text = (TextView) itemView.findViewById(R.id.menu_category_item);
            linearLayout=(LinearLayout)itemView.findViewById(R.id.overall_parentview);
            arrow_iamge=(ImageView)itemView.findViewById(R.id.arrow_click_action);


            if (isExpanded()){
                Log.e("expanded","outsideexpand");
                arrow_iamge.animate().rotation(0).start();
            }else{
                Log.e("Collapased","outsidecollapsed");
                arrow_iamge.animate().rotation(180).start();
            }

            linearLayout.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (isExpanded()){
                        arrow_iamge.animate().rotation(0).start();
                        Log.e("expanded","expanded");
                        collapseView();

                    }else {
                        arrow_iamge.animate().rotation(180).start();
                        Log.e("collapse","collapse");
                        expandView();
                    }
                }


            });




        }

        public void bind(final CategoryItem categoryItem) {
            menu_category_item_text.setText(categoryItem.getCategoryname());
        }

        @Override
        public boolean shouldItemViewClickToggleExpansion() {
            return false;
        }

        @Override
        public void onExpansionToggled(boolean expanded) {
            super.onExpansionToggled(expanded);
        }

        @Override
        public boolean isExpanded() {
            return super.isExpanded();
        }
     }

    public class ProductCateViewHolder extends ChildViewHolder {

        final View rowView;

        private TextView product_name_text, product_price_text, my_cart_quantity, my_cart_decrease, my_cart_increase;

        private View include_layout;

        private Button product_add_btn;
        private ImageView product_image;
        private TextView product_description;


        public ProductCateViewHolder(View itemView) {
            super(itemView);
            rowView = itemView;


            product_name_text = (TextView) rowView.findViewById(R.id.product_name_text);
            product_description = (TextView) rowView.findViewById(R.id.product_description_text);
       
      



        }

        public void bind(final ProductList_Data product_list_item, final int parentPosition) {


         
            product_name_text.setText(product_list_item.getproductName());
            product_description.setText(product_list_item.getDescription());
       
           
        }




    }

**Comment by syedqbuster** [comment]
As normal I Implemented Filterable Class and override getFilter in adapter
and maintain originalData

           @Override
           public Filter getFilter() {
           Filter filter = new Filter() {

            @SuppressWarnings("unchecked")
            @Override
            protected void publishResults(CharSequence constraint, FilterResults results) {
                List groups = (ArrayList<? extends ExpandableGroup>) results.values; // has the filtered values
                getGroups().clear();
                getGroups().addAll(groups);

                notifyDataSetChanged();
            }

            @Override
            protected FilterResults performFiltering(CharSequence constraint) {
                FilterResults results = new FilterResults();        // Holds the results of a filtering operation in values
                ArrayList<MyModelGroup> FilteredArrList = new ArrayList<>();

                if (originalData == null) {
                    originalData = new ArrayList<>(getGroups());
                }

      
                if (constraint == null || constraint.length() == 0) {
                    results.count = originalData.size();
                    results.values = originalData;
                } else {
                    constraint = constraint.toString().toLowerCase();
                    for (int i = 0; i < originalData.size(); i++) {
                        MyModelGroup group = (MyModelGroup) originalData.get(i);

                        if (group != null && group.getTitle() != null) {
                            if (group.getTitle().toLowerCase().contains(constraint))
                                FilteredArrList.add(group);
                        }
                    }
                    // set the Filtered result to return
                    results.count = FilteredArrList.size();
                    results.values = FilteredArrList;

                }
                return results;
            }
        };
        return filter;


    }

**Comment by rajextreme9476** [comment]
public Filter getFilter() {
        return new Filter() {
            @Override
            protected FilterResults performFiltering(CharSequence charSequence) {
                String charString = charSequence.toString();
                if (charString.isEmpty()) {
                    listItemsFilter = items;
                } else {
                     List<ListItem> filterList = new ArrayList<ListItem>();

                    for (int i = 0; i < items.size(); i++) {

                        if(items.get(i).getType() == ListItem.TYPE_HEADER){
                            filterList.add(items.get(i));
                        }else {
                            ContactsItem row = (ContactsItem) items.get(i);
                            if(row.getEvent().getUserName() !=null && row.getEvent().getCellPhone() != null)
                                if (row.getEvent().getUserName().toLowerCase().contains(charString.toLowerCase()) || row.getEvent().getCellPhone().contains(charSequence)) {
                                    filterList.add(row);
                                }
                        }
                    }

                    listItemsFilter = filterList;
                }

                FilterResults filterResults = new FilterResults();
                filterResults.values = listItemsFilter;
                return filterResults;
            }

            @Override
            protected void publishResults(CharSequence charSequence, FilterResults filterResults) {
                listItemsFilter = (ArrayList<ListItem>) filterResults.values;
                notifyDataSetChanged();
            }
        };

If you have any query - ravirajdesai501@gmail.com
![1594543050550](https://user-images.githubusercontent.com/7633802/87242337-5838de00-c449-11ea-9360-329755048a03.jpg)
