### ISSUE TITLE
Expand group with long click

### ISSUE THREAD

**Issue by pmsferreira** [thoughtbot/expandable-recycler-view#95]
How to expand group when long clicked specific group ?

**Comment by sebinpaul** [comment]
How did you achieve this?

**Comment by pmsferreira** [comment]
Hi @sebinpaul I did like this:

        @Override
        public boolean shouldItemViewClickToggleExpansion() { return false; }

        @Override
        public boolean onLongClick(View view) {
            if(isExpanded())
                collapseView();
            else
                expandView();
            return true;
        }
