### ISSUE TITLE
How to expand only one group at a time

### ISSUE THREAD

**Issue by amar0001** [thoughtbot/expandable-recycler-view#97]
How can I expand only one group at a time and collapse the other opened group.

**Comment by babulpatel1309** [comment]
I am also searching for one more problem. Like how to collapse all expanded menus programmatically?

**Comment by babulpatel1309** [comment]
hi @amar0001  found one solution. May be its not proper solution but try this one.

`int tapped =0; //let's say first group tapped`
Store your current open or tapped position and then forloop below code to close the group

```
int groupMembers = 5;

for(int i=0;i<groupMembers;i++){

if (tapped!=i && adapter.isGroupExpanded(2)) {
                    adapter.toggleGroup(2);
                }
}
```


try this solution and let me know if you need any help.

**Comment by jet360** [comment]
collapse animation is not called when I do this 

int groupMembers = 5;

for(int i=0;i<groupMembers;i++){

if (tapped!=i && adapter.isGroupExpanded(2)) {
                    adapter.toggleGroup(2);
                }
}
